In [3]:
import BECancerResistome
import numpy as np
import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt

# MC

### Load Data

In [19]:
#Load Coelho M.A. et al. publication z-score file
mc_zscore = pd.read_csv("data/4_Screen_zscores/MC/MC_zscores_pDNA.csv")

#Load the Beagle generated library
mc_beagle = pd.read_csv("data/1_Beagle_design_files/MC/MC_guides.txt", sep="\t")

#Load the Beagle generated library + UTR guides
mc_beagle_utr = pd.read_csv("data/1_Beagle_design_files/MC/MC_guides+UTR-guides.csv", sep=",", low_memory=False)

In [5]:
mc_zscore.head()

,Guide,Gene,Editor,H23_Adag_RepA,H23_Adag_RepB,H23_Sotor_RepA,H23_Sotor_RepB,H23_T0_RepA,H23_T0_RepB,H_T29_Deb_Cet_RepA,...,H_T29_T0_RepB,H_T29_Tram_RepA,H_T29_Tram_RepB,P_C9_Gefit_RepA,P_C9_Gefit_RepB,P_C9_Gefit_RepC,P_C9_Osim_RepA,P_C9_Osim_RepB,P_C9_T0_RepA,P_C9_T0_RepB
0,AAAAAAAAAAACTAAGAGTT,KRAS,ABE,2.207324,0.402861,0.380062,0.498358,0.679475,-0.234903,-0.376278,...,-0.734241,-0.689801,0.240439,-0.370762,1.908978,NaN,-0.488552,1.837751,-0.158499,-0.000764
1,AAAAAAAAAAACTAAGAGTT,KRAS,CBE,-1.449741,0.918920,-0.479678,0.626708,1.157473,0.264743,1.192417,...,0.468737,0.893703,2.496363,0.562802,2.152187,0.633014,-0.098675,0.476921,-0.139716,-0.328849
2,AAAAAAAAAAGTAAGCTTCA,KRAS,ABE,-1.188256,0.362693,-1.739719,0.661547,-0.935847,-1.540695,0.036072,...,-1.243106,0.548338,-1.459784,-0.265151,0.625855,NaN,-0.785432,-0.331351,-0.492798,-0.541818
3,AAAAAAAAAAGTAAGCTTCA,KRAS,CBE,-0.355967,0.737102,0.167383,-0.420221,-0.166197,0.000072,-0.607708,...,0.047498,-1.650291,-0.109189,-0.871263,-0.700061,-0.462142,0.832627,1.455213,0.324469,-0.294009
4,AAAAAAAAAATCAATGGTGG,BCL2,ABE,-1.144441,-0.043888,-3.221753,1.729673,-2.269742,0.380462,0.423973,...,0.068710,1.035790,0.660678,-0.716366,0.230420,NaN,-1.708553,-0.489586,-0.411487,-0.165079

In [31]:
mc_zscore['Gene'].value_counts()

Gene
BRAF       7220
EGFR       7038
BCL2       5578
PARP1      4276
PIK3CA     4222
           ...
HTR5A         2
CXorf66       2
NCBP2         2
FARSB         2
RAX           2
Name: count, Length: 150, dtype: int64

In [32]:
gene_counts = mc_zscore['Gene'].value_counts()
pd.set_option('display.max_rows', None)
gene_counts

Gene
BRAF                      7220
EGFR                      7038
BCL2                      5578
PARP1                     4276
PIK3CA                    4222
AKT1                      4048
KRAS                      3278
MYC                       2500
MAP2K1                    2310
MAP2K2                    2286
PARP2                     1620
Panlethal splice donor      68
RRM1                         6
RPL8                         6
VPS25                        6
CDC123                       6
RPS4X                        6
CDK1                         6
PRELID1                      6
SNRPA1                       6
SRSF7                        6
RPS16                        6
PSMA1                        6
CDC16                        6
PPWD1                        6
ORC6                         6
EIF2S1                       6
C8B                          6
PRPF8                        6
EIF2S3                       6
RPL18A                       6
DGAT2L6                      6
CHAF1B                       6
RPS20                        6
RPL4                         6
PSMB4                        6
CDC27                        6
RPS13                        6
TPH2                         6
RPS18                        6
GABRA1                       6
PHB2                         6
AURKB                        6
RPL14                        6
ATP6V0C                      6
CDX4                         6
RPL13                        6
XAB2                         6
HSPA9                        6
PSMD14                       6
COPB1                        6
COPB2                        6
RPL12                        6
RPL6                         6
SF1                          6
SLC36A3                      6
PRSS37                       6
PSMA2                        6
KPNB1                        6
ADH7                         6
TOP2A                        6
RPS19                        6
TRPC7                        6
SF3A3                        6
SPEM1                        6
RPS6                         6
PDILT                        6
EIF4A3                       6
GSX2                         6
KLK12                        6
CHEK1                        6
CKAP5                        6
NDST4                        6
UBL5                         6
COPA                         6
HNRNPK                       6
RNGTT                        6
PSMA3                        6
RAN                          6
PLA2G2F                      6
RPL27A                       6
MED11                        6
PSMA7                        6
PRPF38A                      6
LSM2                         6
CSE1L                        6
GFRAL                        6
WEE1                         6
POLR3A                       6
MEP1A                        6
FMR1NB                       6
GTF2B                        6
SERPINA7                     6
RPA1                         6
RPS3                         6
SERPINB12                    6
F13B                         6
RNF17                        6
BUB3                         6
SRSF3                        6
UBA1                         6
GTPBP4                       6
THOC2                        6
CIAO3                        6
RPS12                        6
SLC13A1                      6
POLR1C                       6
GLRA2                        6
DONSON                       6
KIF11                        6
PSMB3                        6
PAFAH1B1                     6
RUVBL2                       6
RPL18                        6
SF3B3                        6
KIF23                        6
RPL11                        6
PRPF19                       6
PUF60                        6
BPIFB6                       6
DTYMK                        6
POLR2C                       6
RPL10A                       6
PSMA6                        6
RPS7                         6
DTL                          6
NSF                          6
RPS8                         6
CCT3                         6
WDR43                        6
MAK16                        6
VCP                          6
YRDC                         4
UTS2R                        4
SNRPD1                       4
RPS11                        4
GPX6                         4
DSPP                         4
ERH                          4
RPL37A                       4
SRSF2                        2
BMP15                        2
FGF4                         2
SNRPD3                       2
APOBEC1                      2
HTR5A                        2
CXorf66                      2
NCBP2                        2
FARSB                        2
RAX                          2
Name: count, dtype: int64

In [33]:
mc_beagle_utr['Target Gene Symbol'].value_counts()

Target Gene Symbol
EGFR      10086
BRAF       8074
PIK3CA     6648
BCL2       6228
PARP1      4440
AKT1       4164
KRAS       3892
MYC        3648
MAP2K1     2846
MAP2K2     2716
PARP2      1872
Name: count, dtype: int64

In [20]:
# Check duplicates in z-score file
print("Duplicates in z-score file:", mc_zscore['Guide'].duplicated().sum())

# Check duplicates in Beagle file
print("Duplicates in Beagle library:", mc_beagle['sgRNA Sequence'].duplicated().sum())

# Check duplicates in Beagle + UTR file
print("Duplicates in Beagle + UTR library:", mc_beagle_utr['sgRNA Sequence'].duplicated().sum())

Duplicates in z-score file: 22625
Duplicates in Beagle library: 11614
Duplicates in Beagle + UTR library: 27322

### Filter files by editor (ABE & CBE)

In [22]:
#Filter files for ABE
mc_zscore_abe = mc_zscore[mc_zscore["Editor"].str.contains("ABE", na=False)]
mc_beagle_abe = mc_beagle[mc_beagle['Edit Type'].str.contains("A-G", na=False)]
mc_beagle_utr_abe = mc_beagle_utr[mc_beagle_utr['Edit Type'].str.contains("A-G", na=False)]

#Filter files for CBE
mc_zscore_cbe = mc_zscore[mc_zscore["Editor"].str.contains("CBE", na=False)]
mc_beagle_cbe = mc_beagle[mc_beagle['Edit Type'].str.contains("C-T", na=False)]
mc_beagle_utr_cbe = mc_beagle_utr[mc_beagle_utr['Edit Type'].str.contains("C-T", na=False)]

In [14]:
mc_beagle_cbe['Target Gene Symbol'].value_counts()

Target Gene Symbol
EGFR      2250
PARP1     1801
PIK3CA    1217
BRAF      1162
AKT1      1111
MAP2K2     964
PARP2      896
MYC        760
MAP2K1     717
BCL2       505
KRAS       216
Name: count, dtype: int64

In [20]:
mc_beagle_abe.head()

,Input,CRISPR Enzyme,Edit Type,Edit Window,Target Taxon,Target Assembly,Target Genome Sequence,Target Gene ID,Target Gene Symbol,Target Gene Strand,...,PAM Sequence,sgRNA Sequence Start Pos. (global),sgRNA Orientation,Nucleotide Edits (global),Guide Edits,Nucleotide Edits,Amino Acid Edits,Mutation Category,Constraint Violations,Note
0,ENST00000644969,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000007.14,ENSG00000157764,BRAF,-,...,TG,140726475,sense,"140726491T>C, 140726488T>C","A_4, A_7","*3A>G, *6A>G","(NC), (NC)","UTR, UTR",NaN,NaN
2,ENST00000644969,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000007.14,ENSG00000157764,BRAF,-,...,TG,140726479,antisense,140726484A>G,A_6,*10T>C,(NC),UTR,NaN,NaN
4,ENST00000644969,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000007.14,ENSG00000157764,BRAF,-,...,AG,140726481,sense,140726495T>C,A_6,2423A>G,Ter808Trp,Missense,NaN,NaN
6,ENST00000644969,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000007.14,ENSG00000157764,BRAF,-,...,AG,140726482,antisense,140726487A>G,A_6,*7T>C,(NC),UTR,NaN,NaN
8,ENST00000644969,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000007.14,ENSG00000157764,BRAF,-,...,GG,140726483,antisense,140726487A>G,A_5,*7T>C,(NC),UTR,NaN,NaN

### Check sgRNA Duplicates

In [23]:
print("Duplicates in z-score cbe file:", mc_zscore_cbe['Guide'].duplicated().sum())
print("Duplicates in Beagle cbe library:", mc_beagle_cbe['sgRNA Sequence'].duplicated().sum())
print("Duplicates in Beagle + UTR cbe library:", mc_beagle_utr_cbe['sgRNA Sequence'].duplicated().sum())

Duplicates in z-score cbe file: 17
Duplicates in Beagle cbe library: 15
Duplicates in Beagle + UTR cbe library: 15

In [26]:
print(mc_zscore_cbe.columns.tolist())

['Guide', 'Gene', 'Editor', 'H23_Adag_RepA', 'H23_Adag_RepB', 'H23_Sotor_RepA', 'H23_Sotor_RepB', 'H23_T0_RepA', 'H23_T0_RepB', 'H_T29_Deb_Cet_RepA', 'H_T29_Deb_Cet_RepB', 'H_T29_Pict_RepA', 'H_T29_Pict_RepB', 'H_T29_T0_RepA', 'H_T29_T0_RepB', 'H_T29_Tram_RepA', 'H_T29_Tram_RepB', 'P_C9_Gefit_RepA', 'P_C9_Gefit_RepB', 'P_C9_Gefit_RepC', 'P_C9_Osim_RepA', 'P_C9_Osim_RepB', 'P_C9_T0_RepA', 'P_C9_T0_RepB']

In [27]:
# All duplicated rows, including both (or more) appearances
duplicates_zscore_cbe_full = mc_zscore_cbe[mc_zscore_cbe.duplicated('Guide', keep=False)]

# Group duplicates toghether
duplicates_zscore_cbe_full = duplicates_zscore_cbe_full.sort_values('Guide')

pd.set_option('display.max_columns', None)  # Show all columns
duplicates_zscore_cbe_full

,Guide,Gene,Editor,H23_Adag_RepA,H23_Adag_RepB,H23_Sotor_RepA,H23_Sotor_RepB,H23_T0_RepA,H23_T0_RepB,H_T29_Deb_Cet_RepA,H_T29_Deb_Cet_RepB,H_T29_Pict_RepA,H_T29_Pict_RepB,H_T29_T0_RepA,H_T29_T0_RepB,H_T29_Tram_RepA,H_T29_Tram_RepB,P_C9_Gefit_RepA,P_C9_Gefit_RepB,P_C9_Gefit_RepC,P_C9_Osim_RepA,P_C9_Osim_RepB,P_C9_T0_RepA,P_C9_T0_RepB
1694,AACTTACATGATACACCCAA,Panlethal splice donor,CBE,-2.064574,-1.266754,-0.563226,-0.622619,0.269957,0.190206,-1.020163,-0.666620,-0.957944,-0.696761,0.300450,-0.067645,-1.540584,-1.526345,-0.198223,0.282520,-0.088537,-0.230811,0.259513,0.402934,-0.727765
1695,AACTTACATGATACACCCAA,Panlethal splice donor,CBE,-2.064574,-1.266754,-0.563226,-0.622619,0.269957,0.190206,-1.020163,-0.666620,-0.957944,-0.696761,0.300450,-0.067645,-1.540584,-1.526345,-0.198223,0.282520,-0.088537,-0.230811,0.259513,0.402934,-0.727765
2526,AAGTTACCTGATTACAATCC,Panlethal splice donor,CBE,-1.901319,-2.243483,-2.849017,-2.395409,-1.067593,-0.891597,0.081460,-0.114582,0.136827,-0.806944,-1.604899,-0.560627,-0.267998,-0.725612,-0.289703,-0.978929,-0.094181,-0.635897,-0.380333,-2.264965,-2.234784
2527,AAGTTACCTGATTACAATCC,Panlethal splice donor,CBE,-1.901319,-2.243483,-2.849017,-2.395409,-1.067593,-0.891597,0.081460,-0.114582,0.136827,-0.806944,-1.604899,-0.560627,-0.267998,-0.725612,-0.289703,-0.978929,-0.094181,-0.635897,-0.380333,-2.264965,-2.234784
4558,ACCTCACCTGGATCTCCACA,Panlethal splice donor,CBE,-2.264295,-3.030477,-1.742994,-2.726373,1.505664,1.704216,0.285492,0.594437,-0.940639,-1.021502,1.314186,1.233678,-0.750498,-0.311960,0.493481,0.686542,-0.434878,-0.119610,0.797048,1.783199,1.249192
4559,ACCTCACCTGGATCTCCACA,Panlethal splice donor,CBE,-2.264295,-3.030477,-1.742994,-2.726373,1.505664,1.704216,0.285492,0.594437,-0.940639,-1.021502,1.314186,1.233678,-0.750498,-0.311960,0.493481,0.686542,-0.434878,-0.119610,0.797048,1.783199,1.249192
5460,ACTTACATGATACACCCAAT,Panlethal splice donor,CBE,-0.930133,0.159525,-0.550035,-0.166854,0.608622,0.769280,0.106465,0.203699,-0.787219,-0.670383,-1.667347,0.111395,-1.034053,-0.352009,1.483119,-0.261073,1.420203,0.508752,0.188125,-0.160217,0.687549
5461,ACTTACATGATACACCCAAT,Panlethal splice donor,CBE,-0.930133,0.159525,-0.550035,-0.166854,0.608622,0.769280,0.106465,0.203699,-0.787219,-0.670383,-1.667347,0.111395,-1.034053,-0.352009,1.483119,-0.261073,1.420203,0.508752,0.188125,-0.160217,0.687549
9731,ATCTTACCAAGGGGTACATC,Panlethal splice donor,CBE,-0.748527,-0.368238,-0.081129,-0.673179,-0.285768,-0.325870,0.416965,0.584072,0.402499,0.064153,-0.043383,-0.477032,0.373759,0.430914,1.082755,1.249305,-0.841284,0.181203,0.330370,-0.506620,-0.045141
9730,ATCTTACCAAGGGGTACATC,Panlethal splice donor,CBE,-0.748527,-0.368238,-0.081129,-0.673179,-0.285768,-0.325870,0.416965,0.584072,0.402499,0.064153,-0.043383,-0.477032,0.373759,0.430914,1.082755,1.249305,-0.841284,0.181203,0.330370,-0.506620,-0.045141
12464,CACTCACCCTCCGGCGGCAG,Panlethal splice donor,CBE,-0.865838,-0.867705,-1.128139,-0.812555,1.359614,0.189407,-0.550070,-0.117022,-0.374220,-1.433082,0.635085,0.573485,-0.715794,-1.036774,-0.137710,0.270812,0.683013,-0.290102,0.027147,0.510618,0.354064
12465,CACTCACCCTCCGGCGGCAG,Panlethal splice donor,CBE,-0.865838,-0.867705,-1.128139,-0.812555,1.359614,0.189407,-0.550070,-0.117022,-0.374220,-1.433082,0.635085,0.573485,-0.715794,-1.036774,-0.137710,0.270812,0.683013,-0.290102,0.027147,0.510618,0.354064
17060,CCTCACCTGGATCTCCACAA,Panlethal splice donor,CBE,-5.046408,-2.924349,-2.695801,-3.481826,1.324874,0.820561,-0.694116,-0.059030,-2.390656,-2.076154,0.235925,1.165711,-1.043451,-1.272227,-0.753430,0.261792,-0.195580,-0.497296,-0.135237,0.881094,0.555837
17061,CCTCACCTGGATCTCCACAA,Panlethal splice donor,CBE,-5.046408,-2.924349,-2.695801,-3.481826,1.324874,0.820561,-0.694116,-0.059030,-2.390656,-2.076154,0.235925,1.165711,-1.043451,-1.272227,-0.753430,0.261792,-0.195580,-0.497296,-0.135237,0.881094,0.555837
17066,CCTCACCTTGATGGGGATGC,Panlethal splice donor,CBE,-0.105779,0.229182,0.072309,-0.101902,0.597657,0.492768,0.468045,0.694850,1.274199,0.593974,-0.780272,0.311386,0.325240,0.959011,0.607792,0.540038,0.395648,0.327840,0.730993,0.312176,1.228137
17067,CCTCACCTTGATGGGGATGC,Panlethal splice donor,CBE,-0.105779,0.229182,0.072309,-0.101902,0.597657,0.492768,0.468045,0.694850,1.274199,0.593974,-0.780272,0.311386,0.325240,0.959011,0.607792,0.540038,0.395648,0.327840,0.730993,0.312176,1.228137
17721,CCTTACCCTCTAAATAAGAA,Panlethal splice donor,CBE,-0.365755,0.795399,0.401180,-0.551395,0.396165,0.393251,0.572870,0.834368,0.334928,0.188903,-0.224299,-0.499786,0.702702,-0.032092,0.132687,1.085150,0.578971,0.082379,0.491602,-1.423251,-0.530538
17720,CCTTACCCTCTAAATAAGAA,Panlethal splice donor,CBE,-0.365755,0.795399,0.401180,-0.551395,0.396165,0.393251,0.572870,0.834368,0.334928,0.188903,-0.224299,-0.499786,0.702702,-0.032092,0.132687,1.085150,0.578971,0.082379,0.491602,-1.423251,-0.530538
20044,CTCACCTTCTTGTTGATCTC,Panlethal splice donor,CBE,-0.230275,0.285946,0.351713,-0.595598,0.472495,0.142285,0.310539,0.457383,-0.330870,-0.247211,-0.215497,-0.100179,0.461329,0.089124,0.576041,0.044532,-0.985164,0.427632,0.144387,-0.879571,0.227859
20045,CTCACCTTCTTGTTGATCTC,Panlethal splice donor,CBE,-0.230275,0.285946,0.351713,-0.595598,0.472495,0.142285,0.310539,0.457383,-0.330870,-0.247211,-0.215497,-0.100179,0.461329,0.089124,0.576041,0.044532,-0.985164,0.427632,0.144387,-0.879571,0.227859
27244,GCCTCACCTTGCGGAGGGTG,Panlethal splice donor,CBE,-0.687763,-0.190206,-0.982467,-0.587187,0.891364,-0.164498,-0.355498,0.589779,-0.581903,-0.484625,-1.854405,-0.764042,-0.930407,-0.381327,-0.021978,0.112461,-0.332547,0.244140,0.288811,-0.134993,-0.170143
27245,GCCTCACCTTGCGGAGGGTG,Panlethal splice donor,CBE,-0.687763,-0.190206,-0.982467,-0.587187,0.891364,-0.164498,-0.355498,0.589779,-0.581903,-0.484625,-1.854405,-0.764042,-0.930407,-0.381327,-0.021978,0.112461,-0.332547,0.244140,0.288811,-0.134993,-0.170143
28092,GCTCACCTGGGTGTGGGCAA,Panlethal splice donor,CBE,-0.106704,0.179770,0.031051,-0.700491,0.144844,0.582194,0.205341,0.211108,-0.115416,-0.015926,-0.550436,-0.279145,-0.151074,-0.109151,0.898396,6.485842,-0.073463,0.177125,-0.169895,-0.049658,-0.348001
28093,GCTCACCTGGGTGTGGGCAA,Panlethal splice donor,CBE,-0.106704,0.179770,0.031051,-0.700491,0.144844,0.582194,0.205341,0.211108,-0.115416,-0.015926,-0.550436,-0.279145,-0.151074,-0.109151,0.898396,6.485842,-0.073463,0.177125,-0.169895,-0.049658,-0.348001
30458,GGCTCACCTGGTGAGGTTCA,Panlethal splice donor,CBE,-3.655329,-3.853254,-4.071065,-3.769268,0.529314,0.515021,0.242964,0.138363,-1.147356,-1.620569,0.596823,0.337696,-1.737740,-1.117145,-0.681742,0.227962,-0.641181,-0.963680,-0.607319,0.790385,0.380595
30459,GGCTCACCTGGTGAGGTTCA,Panlethal splice donor,CBE,-3.655329,-3.853254,-4.071065,-3.769268,0.529314,0.515021,0.242964,0.138363,-1.147356,-1.620569,0.596823,0.337696,-1.737740,-1.117145,-0.681742,0.227962,-0.641181,-0.963680,-0.607319,0.790385,0.380595
35222,TACTCACTGGAATTCCAAGT,Panlethal splice donor,CBE,-3.625569,-5.351189,-3.160376,-4.875063,-0.200268,0.546848,-0.566077,-0.194477,-4.004033,-2.535902,0.169094,0.819785,-2.202481,-2.249294,-0.460105,-1.299455,-1.451779,-1.802120,-1.079177,1.124386,0.402009
35223,TACTCACTGGAATTCCAAGT,Panlethal splice donor,CBE,-3.625569,-5.351189,-3.160376,-4.875063,-0.200268,0.546848,-0.566077,-0.194477,-4.004033,-2.535902,0.169094,0.819785,-2.202481,-2.249294,-0.460105,-1.299455,-1.451779,-1.802120,-1.079177,1.124386,0.402009
36436,TCACCTACCCTCATCCGCGT,Panlethal splice donor,CBE,-1.293289,0.023196,-0.365074,-0.472646,0.169001,1.086455,0.183431,0.544871,0.143506,-0.499572,0.195754,0.036988,0.074315,0.271783,-0.412135,-0.999793,-0.576334,0.129715,-0.287459,1.117833,0.354447
36437,TCACCTACCCTCATCCGCGT,Panlethal splice donor,CBE,-1.293289,0.023196,-0.365074,-0.472646,0.169001,1.086455,0.183431,0.544871,0.143506,-0.499572,0.195754,0.036988,0.074315,0.271783,-0.412135,-0.999793,-0.576334,0.129715,-0.287459,1.117833,0.354447
38068,TCTACCTGATGCTGCATCAA,Panlethal splice donor,CBE,-0.166967,-0.527070,-1.056083,-0.760178,1.190759,1.438490,0.319199,0.500966,0.298387,0.094845,0.792593,0.191590,0.465463,0.199082,0.916951,0.016806,-0.158771,0.042219,0.188812,0.718250,1.017692
38069,TCTACCTGATGCTGCATCAA,Panlethal splice donor,CBE,-0.166967,-0.527070,-1.056083,-0.760178,1.190759,1.438490,0.319199,0.500966,0.298387,0.094845,0.792593,0.191590,0.465463,0.199082,0.916951,0.016806,-0.158771,0.042219,0.188812,0.718250,1.017692
43146,TTCTACCTGATGCTGCATCA,Panlethal splice donor,CBE,-2.479540,-0.964904,-1.954518,-0.599295,0.028524,0.262057,0.197261,0.418301,-0.497940,-0.714758,-0.248913,-0.195408,0.272029,-0.303653,0.234706,-0.697883,-0.873364,0.082923,-0.030721,-0.057783,-0.273139
43147,TTCTACCTGATGCTGCATCA,Panlethal splice donor,CBE,-2.479540,-0.964904,-1.954518,-0.599295,0.028524,0.262057,0.197261,0.418301,-0.497940,-0.714758,-0.248913,-0.195408,0.272029,-0.303653,0.234706,-0.697883,-0.873364,0.082923,-0.030721,-0.057783,-0.273139

In [24]:
# All duplicated rows, including both (or more) appearances
duplicates_beagle_cbe_full = mc_beagle_cbe[mc_beagle_cbe.duplicated('sgRNA Sequence', keep=False)]

# Group duplicates toghether
duplicates_beagle_cbe_full = duplicates_beagle_cbe_full.sort_values('sgRNA Sequence')

pd.set_option('display.max_columns', None)  # Show all columns
duplicates_beagle_cbe_full

,Input,CRISPR Enzyme,Edit Type,Edit Window,Target Taxon,Target Assembly,Target Genome Sequence,Target Gene ID,Target Gene Symbol,Target Gene Strand,Target Transcript ID,Target Domain,sgRNA Sequence,sgRNA Context Sequence,PAM Sequence,sgRNA Sequence Start Pos. (global),sgRNA Orientation,Nucleotide Edits (global),Guide Edits,Nucleotide Edits,Amino Acid Edits,Mutation Category,Constraint Violations,Note
22141,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,AGTTGGCCATGGAGTCGATG,AAGGAGTTGGCCATGGAGTCGATGAGCTGG,AG,4101048,antisense,"4101055C>T, 4101054C>T","C_8, C_7","669G>A, 670G>A","Met223Ile, Ala224Thr","Missense, Missense",NaN,NaN
20635,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,AGTTGGCCATGGAGTCGATG,AAGGAGTTGGCCATGGAGTCGATGAGCTGC,AG,66481831,antisense,"66481843G>A, 66481844G>A","C_8, C_7","657G>A, 658G>A","Met219Ile, Ala220Thr","Missense, Missense",NaN,NaN
22129,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,CACGAAGGAGTTGGCCATGG,TGCCCACGAAGGAGTTGGCCATGGAGTCGA,AG,4101040,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20649,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,CACGAAGGAGTTGGCCATGG,TGCCCACGAAGGAGTTGGCCATGGAGTCGA,AG,66481839,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20017,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,CAGAAGAAGCTGGAGGAGCT,CTTGCAGAAGAAGCTGGAGGAGCTAGAGCT,AG,66435046,sense,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22955,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,CAGAAGAAGCTGGAGGAGCT,CCTGCAGAAGAAGCTGGAGGAGCTGGAACT,GG,4117591,sense,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22127,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,CCATGGCCAACTCCTTCGTG,GACTCCATGGCCAACTCCTTCGTGGGCACG,GG,4101040,sense,4101053G>A;4101052G>A,C_7;C_8,671C>T;672C>T,Ala224Val,Missense,NaN,NaN
20647,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,CCATGGCCAACTCCTTCGTG,GACTCCATGGCCAACTCCTTCGTGGGCACA,GG,66481839,sense,66481845C>T;66481846C>T,C_7;C_8,659C>T;660C>T,Ala220Val,Missense,NaN,NaN
22125,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,CCCACGAAGGAGTTGGCCAT,CGTGCCCACGAAGGAGTTGGCCATGGAGTC,GG,4101038,antisense,4101042C>T,C_5,682G>A,Val228Met,Missense,NaN,NaN
20651,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,CCCACGAAGGAGTTGGCCAT,TGTGCCCACGAAGGAGTTGGCCATGGAGTC,GG,66481841,antisense,66481856G>A,C_5,670G>A,Val224Met,Missense,NaN,NaN
20327,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,CCGTACATCGTGGGCTTCTA,CTCTCCGTACATCGTGGGCTTCTATGGTGC,TG,66436824,sense,66436829C>T,C_6,375C>T,Tyr125Tyr,Silent,NaN,NaN
22589,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,CCGTACATCGTGGGCTTCTA,CTCGCCGTACATCGTGGGCTTCTACGGGGC,CG,4110558,sense,4110572G>A,C_6,387C>T,Tyr129Tyr,Silent,NaN,NaN
22133,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,CTCCATGGCCAACTCCTTCG,TCGACTCCATGGCCAACTCCTTCGTGGGCA,TG,4101042,sense,4101058G>A,C_4,666C>T,Ser222Ser,Silent,NaN,NaN
20643,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,CTCCATGGCCAACTCCTTCG,TCGACTCCATGGCCAACTCCTTCGTGGGCA,TG,66481837,sense,66481840C>T,C_4,654C>T,Ser218Ser,Silent,NaN,NaN
20015,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,CTCCTCCAGCTTCTTCTGCA,CTAGCTCCTCCAGCTTCTTCTGCAAGGCCT,AG,66435044,antisense,"66435057G>A, 66435058G>A;66435060G>A","C_7, C_6;C_4","111G>A, 112G>A;114G>A","Leu37Leu, Glu38Lys","Silent, Missense",NaN,NaN
22961,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,CTCCTCCAGCTTCTTCTGCA,CCAGCTCCTCCAGCTTCTTCTGCAGGTCCA,GG,4117593,antisense,"4117599C>T, 4117598C>T;4117596C>T","C_7, C_6;C_4","123G>A, 124G>A;126G>A","Leu41Leu, Glu42Lys","Silent, Missense",NaN,NaN
20641,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,GAAGGAGTTGGCCATGGAGT,CCACGAAGGAGTTGGCCATGGAGTCGATGA,CG,66481836,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22135,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,GAAGGAGTTGGCCATGGAGT,CCACGAAGGAGTTGGCCATGGAGTCGATGA,CG,4101043,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20639,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,GACTCCATGGCCAACTCCTT,CATCGACTCCATGGCCAACTCCTTCGTGGG,CG,66481835,sense,66481839C>T;66481840C>T,C_5;C_6,653C>T;654C>T,Ser218Phe,Missense,NaN,NaN
22137,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,GACTCCATGGCCAACTCCTT,CATCGACTCCATGGCCAACTCCTTCGTGGG,CG,4101044,sense,4101059G>A;4101058G>A,C_5;C_6,665C>T;666C>T,Ser222Phe,Missense,NaN,NaN
22123,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,GCCCACGAAGGAGTTGGCCA,GCGTGCCCACGAAGGAGTTGGCCATGGAGT,TG,4101037,antisense,4101042C>T;4101040C>T,C_6;C_4,682G>A;684G>A,Val228Ile,Missense,NaN,NaN
20653,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,GCCCACGAAGGAGTTGGCCA,TTGTGCCCACGAAGGAGTTGGCCATGGAGT,TG,66481842,antisense,66481856G>A;66481858G>A,C_6;C_4,670G>A;672G>A,Val224Ile,Missense,NaN,NaN
20637,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,GGAGTTGGCCATGGAGTCGA,CGAAGGAGTTGGCCATGGAGTCGATGAGCT,TG,66481833,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22139,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,GGAGTTGGCCATGGAGTCGA,CGAAGGAGTTGGCCATGGAGTCGATGAGCT,TG,4101046,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20329,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,TAGAAGCCCACGATGTACGG,ACCATAGAAGCCCACGATGTACGGAGAGTT,AG,66436824,antisense,66436836G>A;66436837G>A,C_8;C_7,382G>A;383G>A,Gly128Asn,Missense,NaN,NaN
22591,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,TAGAAGCCCACGATGTACGG,CCCGTAGAAGCCCACGATGTACGGCGAGTT,CG,4110558,antisense,4110565C>T;4110564C>T,C_8;C_7,394G>A;395G>A,Gly132Asn,Missense,NaN,NaN
20645,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,TCCATGGCCAACTCCTTCGT,CGACTCCATGGCCAACTCCTTCGTGGGCAC,GG,66481838,sense,66481845C>T,C_8,659C>T,Ala220Val,Missense,NaN,NaN
22131,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,TCCATGGCCAACTCCTTCGT,CGACTCCATGGCCAACTCCTTCGTGGGCAC,GG,4101041,sense,4101053G>A,C_8,671C>T,Ala224Val,Missense,NaN,NaN
20633,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,TGGCCATGGAGTCGATGAGC,GAGTTGGCCATGGAGTCGATGAGCTGCCCG,TG,66481828,antisense,"66481843G>A, 66481844G>A","C_5, C_4","657G>A, 658G>A","Met219Ile, Ala220Thr","Missense, Missense",NaN,NaN
22143,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,TGGCCATGGAGTCGATGAGC,GAGTTGGCCATGGAGTCGATGAGCTGGCCG,TG,4101051,antisense,"4101055C>T, 4101054C>T","C_5, C_4","669G>A, 670G>A","Met223Ile, Ala224Thr","Missense, Missense",NaN,NaN

In [38]:
mc_zscore_cbe[mc_zscore_cbe['Guide'] == 'AGTTGGCCATGGAGTCGATG']

,Guide,Gene,Editor,H23_Adag_RepA,H23_Adag_RepB,H23_Sotor_RepA,H23_Sotor_RepB,H23_T0_RepA,H23_T0_RepB,H_T29_Deb_Cet_RepA,H_T29_Deb_Cet_RepB,H_T29_Pict_RepA,H_T29_Pict_RepB,H_T29_T0_RepA,H_T29_T0_RepB,H_T29_Tram_RepA,H_T29_Tram_RepB,P_C9_Gefit_RepA,P_C9_Gefit_RepB,P_C9_Gefit_RepC,P_C9_Osim_RepA,P_C9_Osim_RepB,P_C9_T0_RepA,P_C9_T0_RepB
8583,AGTTGGCCATGGAGTCGATG,MAP2K2,CBE,-1.244311,0.12987,0.453338,-0.888756,-0.221276,0.080369,-0.257448,0.616742,-0.963607,0.094528,-0.553924,-0.026372,-0.956975,0.299474,-0.922782,-0.70495,0.363631,-0.439163,-0.137613,-0.589409,-0.49181

In [32]:
# All duplicated rows, including both (or more) appearances
duplicates_beagle_utr_cbe_full = mc_beagle_utr_cbe[mc_beagle_utr_cbe.duplicated('sgRNA Sequence', keep=False)]

# Group duplicates toghether
duplicates_beagle_utr_cbe_full = duplicates_beagle_utr_cbe_full.sort_values('sgRNA Sequence')

pd.set_option('display.max_columns', None)  # Show all columns
duplicates_beagle_utr_cbe_full

,Input,CRISPR Enzyme,Edit Type,Edit Window,Target Taxon,Target Assembly,Target Genome Sequence,Target Gene ID,Target Gene Symbol,Target Gene Strand,Target Transcript ID,Target Domain,sgRNA Sequence,sgRNA Context Sequence,PAM Sequence,sgRNA Sequence Start Pos. (global),sgRNA Orientation,Nucleotide Edits (global),Guide Edits,Nucleotide Edits,Amino Acid Edits,Mutation Category,Constraint Violations,Note,Repeats
22141,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,AGTTGGCCATGGAGTCGATG,AAGGAGTTGGCCATGGAGTCGATGAGCTGG,AG,4101048,antisense,"4101055C>T, 4101054C>T","C_8, C_7","669G>A, 670G>A","Met223Ile, Ala224Thr","Missense, Missense",NaN,NaN,4
20635,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,AGTTGGCCATGGAGTCGATG,AAGGAGTTGGCCATGGAGTCGATGAGCTGC,AG,66481831,antisense,"66481843G>A, 66481844G>A","C_8, C_7","657G>A, 658G>A","Met219Ile, Ala220Thr","Missense, Missense",NaN,NaN,4
22129,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,CACGAAGGAGTTGGCCATGG,TGCCCACGAAGGAGTTGGCCATGGAGTCGA,AG,4101040,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
20649,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,CACGAAGGAGTTGGCCATGG,TGCCCACGAAGGAGTTGGCCATGGAGTCGA,AG,66481839,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
20017,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,CAGAAGAAGCTGGAGGAGCT,CTTGCAGAAGAAGCTGGAGGAGCTAGAGCT,AG,66435046,sense,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
22955,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,CAGAAGAAGCTGGAGGAGCT,CCTGCAGAAGAAGCTGGAGGAGCTGGAACT,GG,4117591,sense,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
22127,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,CCATGGCCAACTCCTTCGTG,GACTCCATGGCCAACTCCTTCGTGGGCACG,GG,4101040,sense,4101053G>A;4101052G>A,C_7;C_8,671C>T;672C>T,Ala224Val,Missense,NaN,NaN,4
20647,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,CCATGGCCAACTCCTTCGTG,GACTCCATGGCCAACTCCTTCGTGGGCACA,GG,66481839,sense,66481845C>T;66481846C>T,C_7;C_8,659C>T;660C>T,Ala220Val,Missense,NaN,NaN,4
22125,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,CCCACGAAGGAGTTGGCCAT,CGTGCCCACGAAGGAGTTGGCCATGGAGTC,GG,4101038,antisense,4101042C>T,C_5,682G>A,Val228Met,Missense,NaN,NaN,4
20651,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,CCCACGAAGGAGTTGGCCAT,TGTGCCCACGAAGGAGTTGGCCATGGAGTC,GG,66481841,antisense,66481856G>A,C_5,670G>A,Val224Met,Missense,NaN,NaN,4
20327,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,CCGTACATCGTGGGCTTCTA,CTCTCCGTACATCGTGGGCTTCTATGGTGC,TG,66436824,sense,66436829C>T,C_6,375C>T,Tyr125Tyr,Silent,NaN,NaN,4
22589,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,CCGTACATCGTGGGCTTCTA,CTCGCCGTACATCGTGGGCTTCTACGGGGC,CG,4110558,sense,4110572G>A,C_6,387C>T,Tyr129Tyr,Silent,NaN,NaN,4
22133,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,CTCCATGGCCAACTCCTTCG,TCGACTCCATGGCCAACTCCTTCGTGGGCA,TG,4101042,sense,4101058G>A,C_4,666C>T,Ser222Ser,Silent,NaN,NaN,4
20643,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,CTCCATGGCCAACTCCTTCG,TCGACTCCATGGCCAACTCCTTCGTGGGCA,TG,66481837,sense,66481840C>T,C_4,654C>T,Ser218Ser,Silent,NaN,NaN,4
20015,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,CTCCTCCAGCTTCTTCTGCA,CTAGCTCCTCCAGCTTCTTCTGCAAGGCCT,AG,66435044,antisense,"66435057G>A, 66435058G>A;66435060G>A","C_7, C_6;C_4","111G>A, 112G>A;114G>A","Leu37Leu, Glu38Lys","Silent, Missense",NaN,NaN,4
22961,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,CTCCTCCAGCTTCTTCTGCA,CCAGCTCCTCCAGCTTCTTCTGCAGGTCCA,GG,4117593,antisense,"4117599C>T, 4117598C>T;4117596C>T","C_7, C_6;C_4","123G>A, 124G>A;126G>A","Leu41Leu, Glu42Lys","Silent, Missense",NaN,NaN,4
20641,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,GAAGGAGTTGGCCATGGAGT,CCACGAAGGAGTTGGCCATGGAGTCGATGA,CG,66481836,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
22135,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,GAAGGAGTTGGCCATGGAGT,CCACGAAGGAGTTGGCCATGGAGTCGATGA,CG,4101043,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
20639,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,GACTCCATGGCCAACTCCTT,CATCGACTCCATGGCCAACTCCTTCGTGGG,CG,66481835,sense,66481839C>T;66481840C>T,C_5;C_6,653C>T;654C>T,Ser218Phe,Missense,NaN,NaN,4
22137,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,GACTCCATGGCCAACTCCTT,CATCGACTCCATGGCCAACTCCTTCGTGGG,CG,4101044,sense,4101059G>A;4101058G>A,C_5;C_6,665C>T;666C>T,Ser222Phe,Missense,NaN,NaN,4
22123,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,GCCCACGAAGGAGTTGGCCA,GCGTGCCCACGAAGGAGTTGGCCATGGAGT,TG,4101037,antisense,4101042C>T;4101040C>T,C_6;C_4,682G>A;684G>A,Val228Ile,Missense,NaN,NaN,4
20653,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,GCCCACGAAGGAGTTGGCCA,TTGTGCCCACGAAGGAGTTGGCCATGGAGT,TG,66481842,antisense,66481856G>A;66481858G>A,C_6;C_4,670G>A;672G>A,Val224Ile,Missense,NaN,NaN,4
20637,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,GGAGTTGGCCATGGAGTCGA,CGAAGGAGTTGGCCATGGAGTCGATGAGCT,TG,66481833,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
22139,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,GGAGTTGGCCATGGAGTCGA,CGAAGGAGTTGGCCATGGAGTCGATGAGCT,TG,4101046,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
20329,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,TAGAAGCCCACGATGTACGG,ACCATAGAAGCCCACGATGTACGGAGAGTT,AG,66436824,antisense,66436836G>A;66436837G>A,C_8;C_7,382G>A;383G>A,Gly128Asn,Missense,NaN,NaN,4
22591,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,TAGAAGCCCACGATGTACGG,CCCGTAGAAGCCCACGATGTACGGCGAGTT,CG,4110558,antisense,4110565C>T;4110564C>T,C_8;C_7,394G>A;395G>A,Gly132Asn,Missense,NaN,NaN,4
20645,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,TCCATGGCCAACTCCTTCGT,CGACTCCATGGCCAACTCCTTCGTGGGCAC,GG,66481838,sense,66481845C>T,C_8,659C>T,Ala220Val,Missense,NaN,NaN,4
22131,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,TCCATGGCCAACTCCTTCGT,CGACTCCATGGCCAACTCCTTCGTGGGCAC,GG,4101041,sense,4101053G>A,C_8,671C>T,Ala224Val,Missense,NaN,NaN,4
20633,ENST00000307102,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,ENST00000307102.10,CDS,TGGCCATGGAGTCGATGAGC,GAGTTGGCCATGGAGTCGATGAGCTGCCCG,TG,66481828,antisense,"66481843G>A, 66481844G>A","C_5, C_4","657G>A, 658G>A","Met219Ile, Ala220Thr","Missense, Missense",NaN,NaN,4
22143,ENST00000262948,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,ENST00000262948.10,CDS,TGGCCATGGAGTCGATGAGC,GAGTTGGCCATGGAGTCGATGAGCTGGCCG,TG,4101051,antisense,"4101055C>T, 4101054C>T","C_5, C_4","669G>A, 670G>A","Met223Ile, Ala224Thr","Missense, Missense",NaN,NaN,4

In [34]:
mc_zscore[mc_zscore['Gene'] == 'RPS20']

,Guide,Gene,Editor,H23_Adag_RepA,H23_Adag_RepB,H23_Sotor_RepA,H23_Sotor_RepB,H23_T0_RepA,H23_T0_RepB,H_T29_Deb_Cet_RepA,H_T29_Deb_Cet_RepB,H_T29_Pict_RepA,H_T29_Pict_RepB,H_T29_T0_RepA,H_T29_T0_RepB,H_T29_Tram_RepA,H_T29_Tram_RepB,P_C9_Gefit_RepA,P_C9_Gefit_RepB,P_C9_Gefit_RepC,P_C9_Osim_RepA,P_C9_Osim_RepB,P_C9_T0_RepA,P_C9_T0_RepB
5602,ACTTTACCTTGGTAGGCATT,RPS20,ABE,-2.346164,-2.321536,-0.986568,-1.321128,0.010563,0.152013,-4.531436,-2.332343,-5.227367,-5.642763,-0.377966,-0.212962,-3.182291,-3.356181,-6.154700,-4.525375,NaN,-5.421830,-4.328474,-0.409563,-0.772672
5603,ACTTTACCTTGGTAGGCATT,RPS20,CBE,-4.178064,-3.534879,-3.623656,-3.422543,0.609332,0.473130,-0.308679,-0.347763,-2.074048,-2.132279,-0.999087,0.507934,-1.855629,-1.756536,-2.155790,-1.072111,-0.717302,-1.704640,-1.707137,0.668025,-0.421969
19996,CTCACCATGGCTGTTGCGCG,RPS20,ABE,-1.901783,-3.072270,-2.253964,-2.145893,-1.562344,-0.954151,-0.375833,-0.938411,-2.574836,-2.411863,-1.015116,-0.907432,-1.111202,-1.010095,-3.424658,-4.025346,NaN,-3.861889,-3.373692,-0.922447,-0.396058
19997,CTCACCATGGCTGTTGCGCG,RPS20,CBE,-2.611546,-2.007531,-1.978845,-2.602807,-0.207238,-0.373473,0.048889,0.400142,-0.326631,-0.393037,-1.206402,-0.969924,-0.344409,-0.113246,2.893856,0.132943,-1.473483,-0.967577,-0.023235,-0.866334,-0.100183
27236,GCCTCACCATGGCTGTTGCG,RPS20,ABE,0.721766,1.135737,0.007872,0.253636,-0.676882,0.341671,-0.887271,-0.211910,-0.079272,-0.463644,1.097245,0.617649,0.311446,-0.115096,-1.058929,-0.843126,NaN,-1.426532,-1.875227,0.211550,0.565455
27237,GCCTCACCATGGCTGTTGCG,RPS20,CBE,0.567522,0.166979,-0.292235,0.441069,1.027896,1.234743,1.336392,1.180344,0.485741,0.945018,0.876819,0.518734,0.931795,0.426556,0.328610,0.243299,0.912714,0.512887,0.501798,0.811036,0.714832

In [28]:
#check actual duplicates
duplicates = mc_zscore[mc_zscore.duplicated(keep=False)]

In [30]:
len(duplicates)

68

In [29]:
duplicates.head()

,Guide,Gene,Editor,H23_Adag_RepA,H23_Adag_RepB,H23_Sotor_RepA,H23_Sotor_RepB,H23_T0_RepA,H23_T0_RepB,H_T29_Deb_Cet_RepA,H_T29_Deb_Cet_RepB,H_T29_Pict_RepA,H_T29_Pict_RepB,H_T29_T0_RepA,H_T29_T0_RepB,H_T29_Tram_RepA,H_T29_Tram_RepB,P_C9_Gefit_RepA,P_C9_Gefit_RepB,P_C9_Gefit_RepC,P_C9_Osim_RepA,P_C9_Osim_RepB,P_C9_T0_RepA,P_C9_T0_RepB
1692,AACTTACATGATACACCCAA,Panlethal splice donor,ABE,-4.176083,-8.835617,-7.923377,-6.012381,-2.348941,-2.140912,-13.970736,-7.278630,-15.140538,-10.080368,-0.029406,-1.916993,-9.863020,-9.728702,-7.965490,-6.195366,NaN,-9.244200,-7.909407,-0.453144,0.049367
1693,AACTTACATGATACACCCAA,Panlethal splice donor,ABE,-4.176083,-8.835617,-7.923377,-6.012381,-2.348941,-2.140912,-13.970736,-7.278630,-15.140538,-10.080368,-0.029406,-1.916993,-9.863020,-9.728702,-7.965490,-6.195366,NaN,-9.244200,-7.909407,-0.453144,0.049367
1694,AACTTACATGATACACCCAA,Panlethal splice donor,CBE,-2.064574,-1.266754,-0.563226,-0.622619,0.269957,0.190206,-1.020163,-0.666620,-0.957944,-0.696761,0.300450,-0.067645,-1.540584,-1.526345,-0.198223,0.282520,-0.088537,-0.230811,0.259513,0.402934,-0.727765
1695,AACTTACATGATACACCCAA,Panlethal splice donor,CBE,-2.064574,-1.266754,-0.563226,-0.622619,0.269957,0.190206,-1.020163,-0.666620,-0.957944,-0.696761,0.300450,-0.067645,-1.540584,-1.526345,-0.198223,0.282520,-0.088537,-0.230811,0.259513,0.402934,-0.727765
2524,AAGTTACCTGATTACAATCC,Panlethal splice donor,ABE,-0.693714,-1.874422,-1.296735,-2.071950,-0.886539,-2.262680,-1.186473,-1.410195,-3.330962,-3.419200,-2.146151,-1.950796,-2.824717,-1.879357,-5.042640,-3.754737,NaN,-5.304223,-3.468418,-3.133664,-1.599048