In [1]:
import BECancerResistome
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import re
import math
from sklearn.preprocessing import OrdinalEncoder

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Load Data

## Current Annotated dataset

In [3]:
annotated_control_foldx_df = pd.read_csv("/data/benchmarks/genomic_annot/zscores-unambiguous-VEPannotated-processed-gene-expression-foldx-control.csv")

/tmp/ipykernel_1353803/509366020.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  annotated_control_foldx_df = pd.read_csv("/data/benchmarks/genomic_annot/zscores-unambiguous-VEPannotated-processed-gene-expression-foldx-control.csv")

In [8]:
annotated_control_foldx_df.head()

,Guide,Editor,Gene,Cell_Line,Drug,zscore,Hit_class,Source,Target Transcript ID,uniprot_accession,RefSeq match transcript (MANE Select),Amino Acid Edits,aa_change,Mutation_Category_enc,IMPACT_enc,TSL,SIFT_pathogenicity,PolyPhen_pathogenicity,REVEL,ClinPred,EVE_SCORE,AlphaMissense_score,BayesDel_noAF_score,DANN_score,DEOGEN2_score,ESM1b_score,Eigen-PC-phred_coding,Eigen-PC-raw_coding,GERP++_NR,GERP++_RS,LIST-S2_score,MPC_rankscore,MPC_score,MVP_score,MetaRNN_score,MetaSVM_score,MutFormer_score,MutationAssessor_score,PROVEAN_score,PrimateAI_pred_enc,VARITY_R_LOO_score,bStatistic,fathmm-XF_coding_score,gMVP_score,phastCons100way_vertebrate,phyloP100way_vertebrate,CADD_PHRED,MaxEntScan_alt,MaxEntScan_diff,MaxEntScan_ref,SpliceAI_pred_DP_AG,SpliceAI_pred_DP_AL,SpliceAI_pred_DP_DG,SpliceAI_pred_DP_DL,SpliceAI_pred_DS_AG,SpliceAI_pred_DS_AL,SpliceAI_pred_DS_DG,SpliceAI_pred_DS_DL,BLOSUM62,LOEUF,mutfunc_exp,ada_score,Gene_expression_expected_counts,Gene_expression_voom,wild_type,uniprot_position,mutated_type,foldx_ddg,plddt
0,AAAAAACATCGTAGTAGCAG,CBE,RICTOR,A375,PIC,0.274277,non-hit,NaN,ENST00000357387.8,Q6R327,NM_152756.5,His1109Tyr,H1109Y,3.0,2.0,1.0,1.0,0.000,0.214,0.463040,NaN,0.0685,-0.402171,0.970933,0.045001,-4.388,5.314964,0.516773,5.75,5.75,0.917608,0.44121,0.445060,0.093490,0.179100,-1.0259,0.000785,0.345,-0.22,1.0,0.094767,226.0,0.800526,NaN,1.000,5.938,20.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.305,NaN,NaN,2813.00,5.531900,H,1109.0,Y,NaN,NaN
1,AAAAAACTCAACAGCAGTGA,CBE,NRAS,A375,PIC,0.399691,non-hit,NaN,ENST00000369535.5,P01111,NM_002524.5,Leu171Phe,L171F,3.0,2.0,1.0,0.1,NaN,0.141,0.413488,NaN,0.1149,-0.222424,0.993713,0.120039,-5.943,3.683551,0.294249,5.86,5.86,0.865513,0.74516,1.008632,0.619943,0.190982,-0.9613,0.907693,1.385,-1.28,1.0,0.072730,819.0,0.580949,0.628916,1.000,4.055,23.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.550,NaN,NaN,6331.00,6.702081,L,171.0,F,-0.239753,88.23
2,AAAAAACTGGCCAGGTGAGC,CBE,PIK3CB,A375,PIC,0.399178,non-hit,NaN,ENST00000674063.1,P42338,NM_006219.3,Thr930Ile,T930I,3.0,2.0,NaN,0.0,0.862,NaN,0.373381,NaN,NaN,-0.058094,0.998396,0.879846,-10.191,4.891242,0.469329,5.63,3.78,NaN,0.73854,NaN,NaN,NaN,0.6434,0.529280,3.705,NaN,0.0,0.365695,856.0,0.310513,NaN,0.998,2.094,25.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.319,NaN,NaN,3356.00,5.786491,T,930.0,I,-0.070749,91.70
3,AAAAAACTGTTTGGGACCTC,CBE,EGFR,A375,PIC,-0.801011,non-hit,NaN,ENST00000275493.7,P00533,NM_005228.5,Leu480Leu,L480L,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.051,NaN,NaN,NaN,21.0,-44.0,-45.0,45.0,0.0,0.0,0.0,0.0,NaN,0.475,-0.01879,NaN,891.97,3.875409,L,480.0,L,NaN,NaN
4,AAAAAATCCAGCGTCTAAGC,CBE,MYC,A375,PIC,-0.379377,non-hit,NaN,ENST00000621592.8,P01106,NM_002467.6,Asp2Asn,D2N,3.0,2.0,1.0,0.0,0.199,NaN,0.453567,NaN,0.1399,-0.438067,0.984375,NaN,NaN,1.792897,-0.197017,4.31,2.43,0.397160,NaN,NaN,0.733174,0.215208,-0.7405,0.036037,NaN,NaN,1.0,NaN,951.0,0.226082,0.128201,1.000,1.507,22.100,NaN,NaN,NaN,16.0,-14.0,10.0,26.0,0.0,0.0,0.0,0.0,1.0,0.128,NaN,NaN,783.00,3.687539,D,2.0,N,-0.237760,55.70

In [9]:
len(annotated_control_foldx_df)

147085

## Samples

In [5]:
foldx_sample = pd.read_csv('data/9_ProtVar/Samples/2025.02.10_foldx_energy_sample.csv')
pockets_sample = pd.read_csv('data/9_ProtVar/Samples/2024.05.28_pockets_sample.tsv', sep='\t')
interfaces_sample = pd.read_csv('data/9_ProtVar/Samples/2024.05.28_interface_summary_sample.tsv', sep='\t')

In [ ]:
foldx_sample.head()

In [ ]:
pockets_sample.head()

In [ ]:
interfaces_sample.head()

In [19]:
#Create a txt file with all target transcript IDs
transcript_ids = annotated_control_df['Target Transcript ID'].unique()
with open('data/9_ProtVar/Ensembl_transcript_ids.txt', 'w') as f:
    for transcript_id in transcript_ids:
        f.write(f"{transcript_id}\n")

In [ ]:
#Open excel file with mapping of transcript IDs to UniProt IDs
transcript_to_uniprot_df = pd.read_excel('data/9_ProtVar/idmapping_2025_10_27.xlsx')

In [ ]:
transcript_to_uniprot_df

### Check if protein sequence from the Ensembl Transcript and the UniProt protein match

In [147]:
ensembl_sequence = """MAARRRRSTGGGRARALNESKRVNNGNTAPEDSSPAKKTRRCQRQESKKMPVAGGKANKD
RTEDKQDESVKALLLKGKAPVDPECTAKVGKAHVYCEGNDVYDVMLNQTNLQFNNNKYYL
IQLLEDDAQRNFSVWMRWGRVGKMGQHSLVACSGNLNKAKEIFQKKFLDKTKNNWEDREK
FEKVPGKYDMLQMDYATNTQDEEETKKEESLKSPLKPESQLDLRVQELIKLICNVQAMEE
MMMEMKYNTKKAPLGKLTVAQIKAGYQSLKKIEDCIRAGQHGRALMEACNEFYTRIPHDF
GLRTPPLIRTQKELSEKIQLLEALGDIEIAIKLVKTELQSPEHPLDQHYRNLHCALRPLD
HESYEFKVISQYLQSTHAPTHSDYTMTLLDLFEVEKDGEKEAFREDLHNRMLLWHGSRMS
NWVGILSHGLRIAPPEAPITGYMFGKGIYFADMSSKSANYCFASRLKNTGLLLLSEVALG
QCNELLEANPKAEGLLQGKHSTKGLGKMAPSSAHFVTLNGSTVPLGPASDTGILNPDGYT
LNYNEYIVYNPNQVRMRYLLKVQFNFLQLW"""

ensembl_sequence= ''.join(ensembl_sequence.split())

In [150]:
uniprot_sequence = "MAARRRRSTGGGRARALNESKRVNNGNTAPEDSSPAKKTRRCQRQESKKMPVAGGKANKDRTEDKQDESVKALLLKGKAPVDPECTAKVGKAHVYCEGNDVYDVMLNQTNLQFNNNKYYLIQLLEDDAQRNFSVWMRWGRVGKMGQHSLVACSGNLNKAKEIFQKKFLDKTKNNWEDREKFEKVPGKYDMLQMDYATNTQDEEETKKEESLKSPLKPESQLDLRVQELIKLICNVQAMEEMMMEMKYNTKKAPLGKLTVAQIKAGYQSLKKIEDCIRAGQHGRALMEACNEFYTRIPHDFGLRTPPLIRTQKELSEKIQLLEALGDIEIAIKLVKTELQSPEHPLDQHYRNLHCALRPLDHESYEFKVISQYLQSTHAPTHSDYTMTLLDLFEVEKDGEKEAFREDLHNRMLLWHGSRMSNWVGILSHGLRIAPPEAPITGYMFGKGIYFADMSSKSANYCFASRLKNTGLLLLSEVALGQCNELLEANPKAEGLLQGKHSTKGLGKMAPSSAHFVTLNGSTVPLGPASDTGILNPDGYTLNYNEYIVYNPNQVRMRYLLKVQFNFLQLW"

In [ ]:
ensembl_sequence == uniprot_sequence

In [184]:
transcript_mapping= pd.read_csv("data/transcriptID_mapping.csv")

In [175]:
#drop columns unnamed 5 and unnamed 6
transcript_mapping = transcript_mapping.drop(columns=['Unnamed: 5', 'Unnamed: 6'])

In [180]:
transcript_mapping.to_csv("data/transcriptID_mapping.csv", sep=',', index=False)

In [ ]:
transcript_mapping

In [ ]:
MC_EG_proteins_uniprot={
    'P00533',
    'P01116',
    'P01111',
    'P01112',
    'P15056',
    'P04049',
    'P21860',
    'P04626',
    'P28482',
    'P27361',
    'Q02750',
    'P36507',
    'P42336',
    'P42338',
    'O00329',
    'P31749',
    'P01106',
    'P29353',
    'P62993',
    'Q13480',
    'P26006',
    'P08069',
    'P21802',
    'P42345',
    'Q6R327',
    'P21359',
    'P60484',
    'P14618',
    'Q53GA4',
    'P52209',
    'P10415',
    'P09874',
    'Q9UGN5'
}

# Predicted Changes in Stability

In [5]:
#run on server
foldx = pd.read_csv('/data/benchmarks/genomic_annot/afdb_foldx_export_20250210.csv')

In [ ]:
foldx.shape

In [ ]:
foldx.head()

In [ ]:
#Check if uniprot_acession_proteins are in foldx dataset - 'True' if they are
set(MC_EG_proteins_uniprot).issubset(set(foldx['uniprot_accession'].unique()))

## Merge foldx_ddg with the annotated dataset

In [ ]:
#Load the transcript mapping ID dataset
transcriptID_mapping = pd.read_csv('/data/benchmarks/genomic_annot/transcriptID_mapping.csv', sep=';')

In [ ]:
transcriptID_mapping

In [10]:
#Map Ensembl Transcript to uniprot accession
mapping_dict = dict(zip(transcriptID_mapping["TranscriptID_Ensembl_isoform"], transcriptID_mapping["UniProtID_global"]))
annotated_control_df["uniprot_accession"] = annotated_control_df["Target Transcript ID"].map(mapping_dict)

In [11]:
# Change column position
cols = list(annotated_control_df.columns)

idx = cols.index("Target Transcript ID")
cols.remove("uniprot_accession")
cols.insert(idx + 1, "uniprot_accession")

annotated_control_df = annotated_control_df[cols]

In [ ]:
annotated_control_df.head(20)

#### Get wild type, mutated type and AA position from 'Amino Acid Edits'

In [13]:
#Apply convert_variant to generate "H1109Y"-like string

# Create a mask for non-NC entries
mask = annotated_control_df["Amino Acid Edits"] != "(NC)"

# Apply conversion function only to valid entries
annotated_control_df.loc[mask, "aa_change"] = annotated_control_df.loc[mask, "Amino Acid Edits"].map(
    BECancerResistome.convert_amino_acid_variants
)

# Fill the others with "(NC)" if needed
annotated_control_df.loc[~mask, "aa_change"] = "(NC)"

In [14]:
# Change column position
cols = list(annotated_control_df.columns)

idx = cols.index("Amino Acid Edits")
cols.remove("aa_change")
cols.insert(idx + 1, "aa_change")

annotated_control_df = annotated_control_df[cols]

In [15]:
#Split aa_change into wild_type, position, mutated_type (with NC masking)

annotated_control_df.loc[mask, "wild_type"] = annotated_control_df.loc[mask, "aa_change"].str[0]
annotated_control_df.loc[mask, "uniprot_position"] = annotated_control_df.loc[mask, "aa_change"].str[1:-1].astype(int)
annotated_control_df.loc[mask, "mutated_type"] = annotated_control_df.loc[mask, "aa_change"].str[-1]

# Fill rest with NaN
annotated_control_df.loc[~mask, ["wild_type", "uniprot_position", "mutated_type"]] = np.nan

In [ ]:
annotated_control_df.head()

#### Merge foldx_ddg

In [19]:
#Filter foldX for the proteins used in our study
# Excluding  proteins for which our study uses an alternative isoform - 'P01116', 'P29353', 'Q9UGN5'(the data will be obtained later with FoldX)

uniprot_canonical_isoforms = transcriptID_mapping[transcriptID_mapping['is_canonical_in_uniprot']==True]['UniProtID_global']

foldx_proteins_of_interest = foldx[foldx['uniprot_accession'].isin(uniprot_canonical_isoforms)]

#foldx_proteins_of_interest = foldx[~foldx['uniprot_accession'].isin(['P01116', 'P29353', 'Q9UGN5'])]

In [ ]:
foldx_proteins_of_interest.shape

In [ ]:
foldx_proteins_of_interest['uniprot_accession'].value_counts()

In [26]:
#Save the foldx_proteins_of_interest
foldx_proteins_of_interest.to_csv('/data/benchmarks/genomic_annot/foldx_filtered_proteins_of_interest.csv')

In [28]:
annotated_foldx_control_df = annotated_control_df.merge(
    foldx_proteins_of_interest[["uniprot_accession", "uniprot_position", "wild_type", "mutated_type", "foldx_ddg", "plddt"]],
    how="left",
    on=["uniprot_accession", "uniprot_position", "wild_type", "mutated_type"]
)

In [ ]:
annotated_foldx_control_df.head(20)

In [38]:
#Save the annotated dataset
annotated_foldx_control_df.to_csv("/data/benchmarks/genomic_annot/zscores-unambiguous-VEPannotated-processed-gene-expression-foldx-control.csv")

In [ ]:
annotated_foldx_control_df[annotated_foldx_control_df['uniprot_accession']=='P01116']['foldx_ddg'].head()

#### Checking the duplicates due to aa being in different AlphaFold fragments

In [47]:
#Load annotated dataset with ProtVar foldX data
annotated_foldx_control_df = pd.read_csv("data/9_ProtVar/zscores-unambiguous-VEPannotated-processed-gene-expression-foldx-control.csv")

/var/folders/ry/v0cp3ptj55qfs_pd6_cghmzm0000gn/T/ipykernel_16472/3345242723.py:2: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  annotated_foldx_control_df = pd.read_csv("data/9_ProtVar/zscores-unambiguous-VEPannotated-processed-gene-expression-foldx-control.csv")

In [48]:
len(annotated_foldx_control_df)

147559

In [49]:
len(annotated_control_df)

147319

In [78]:
#Check the duplicates in annotated_foldx_control_df for the same variant due to the amino acid being in different Alphafold fragments
duplicates_fragments = annotated_foldx_control_df[annotated_foldx_control_df.duplicated(
    subset=["Guide", "Editor", "Cell_Line", "Drug", "uniprot_accession", "uniprot_position", "wild_type", "mutated_type", "zscore"], keep=False
)].sort_values(["uniprot_accession", "uniprot_position",  "Guide", "Editor", "Cell_Line", "Drug", "wild_type", "mutated_type"])

In [75]:
#There are duplicates that appear more than 2 times (aa in 3 AlphaFold fragments)
#Check how many unique rows (expect ddG and pLDDT) are repeated 2 times and 3 times
duplicates= annotated_foldx_control_df.duplicated(
    subset=["Guide", "Editor", "Cell_Line", "Drug", "uniprot_accession", "uniprot_position", "wild_type", "mutated_type", "zscore"], keep=False
)
duplicates_fragments_counts = annotated_foldx_control_df[duplicates].groupby(
    ["Guide", "Editor", "Cell_Line", "Drug", "uniprot_accession", "uniprot_position", "wild_type", "mutated_type", "zscore"]
).size()

print(f'Guide + variant + condition repeated 2 times (aa in 2 AlphaFold fragments): {duplicates_fragments_counts.value_counts().get(2,0)}')
print(f'Guide + variant + condition repeated 3 times (aa in 3 AlphaFold fragments): {duplicates_fragments_counts.value_counts().get(3,0)}')

Guide + variant + condition repeated 2 times (aa in 2 AlphaFold fragments): 228
Guide + variant + condition repeated 3 times (aa in 3 AlphaFold fragments): 6

In [76]:
duplicates_fragments.head()

,Guide,Editor,Gene,Cell_Line,Drug,zscore,Hit_class,Source,Target Transcript ID,uniprot_accession,RefSeq match transcript (MANE Select),Amino Acid Edits,aa_change,Mutation_Category_enc,IMPACT_enc,TSL,SIFT_pathogenicity,PolyPhen_pathogenicity,REVEL,ClinPred,EVE_SCORE,AlphaMissense_score,BayesDel_noAF_score,DANN_score,DEOGEN2_score,ESM1b_score,Eigen-PC-phred_coding,Eigen-PC-raw_coding,GERP++_NR,GERP++_RS,LIST-S2_score,MPC_rankscore,MPC_score,MVP_score,MetaRNN_score,MetaSVM_score,MutFormer_score,MutationAssessor_score,PROVEAN_score,PrimateAI_pred_enc,VARITY_R_LOO_score,bStatistic,fathmm-XF_coding_score,gMVP_score,phastCons100way_vertebrate,phyloP100way_vertebrate,CADD_PHRED,MaxEntScan_alt,MaxEntScan_diff,MaxEntScan_ref,SpliceAI_pred_DP_AG,SpliceAI_pred_DP_AL,SpliceAI_pred_DP_DG,SpliceAI_pred_DP_DL,SpliceAI_pred_DS_AG,SpliceAI_pred_DS_AL,SpliceAI_pred_DS_DG,SpliceAI_pred_DS_DL,BLOSUM62,LOEUF,mutfunc_exp,ada_score,Gene_expression_expected_counts,Gene_expression_voom,wild_type,uniprot_position,mutated_type,foldx_ddg,plddt
38928,GTGTTTCACCAAACATATTT,CBE,NF1,A375,LIN,-0.068827,non-hit,NaN,ENST00000358273.9,P21359,NM_001042492.3,Glu445Lys,E445K,3.0,2.0,1.0,0.0,0.057,0.343,0.9605,0.096584,0.6491,-0.044299,0.999163,0.812706,-5.505,5.781303,0.562291,6.17,6.17,0.983668,0.65488,0.789613,0.815019,0.489632,-0.3391,0.999537,1.04,-2.67,0.0,0.643356,656.0,0.898995,0.518561,1.0,9.533,26.4,NaN,NaN,NaN,19.0,-48.0,-3.0,24.0,0.0,0.0,0.0,0.0,1.0,0.249,NaN,NaN,8270.7,7.087630,E,445.0,K,-0.011413,89.07
10762,GTGTTTCACCAAACATATTT,CBE,NF1,A375,PIC,-0.804440,non-hit,NaN,ENST00000358273.9,P21359,NM_001042492.3,Glu445Lys,E445K,3.0,2.0,1.0,0.0,0.057,0.343,0.9605,0.096584,0.6491,-0.044299,0.999163,0.812706,-5.505,5.781303,0.562291,6.17,6.17,0.983668,0.65488,0.789613,0.815019,0.489632,-0.3391,0.999537,1.04,-2.67,0.0,0.643356,656.0,0.898995,0.518561,1.0,9.533,26.4,NaN,NaN,NaN,19.0,-48.0,-3.0,24.0,0.0,0.0,0.0,0.0,1.0,0.249,NaN,NaN,8270.7,7.087630,E,445.0,K,-0.011413,89.07
24845,GTGTTTCACCAAACATATTT,CBE,NF1,A375,SCH,-0.890922,non-hit,NaN,ENST00000358273.9,P21359,NM_001042492.3,Glu445Lys,E445K,3.0,2.0,1.0,0.0,0.057,0.343,0.9605,0.096584,0.6491,-0.044299,0.999163,0.812706,-5.505,5.781303,0.562291,6.17,6.17,0.983668,0.65488,0.789613,0.815019,0.489632,-0.3391,0.999537,1.04,-2.67,0.0,0.643356,656.0,0.898995,0.518561,1.0,9.533,26.4,NaN,NaN,NaN,19.0,-48.0,-3.0,24.0,0.0,0.0,0.0,0.0,1.0,0.249,NaN,NaN,8270.7,7.087630,E,445.0,K,-0.011413,89.07
81177,GTGTTTCACCAAACATATTT,CBE,NF1,HT29,LIN,-0.346173,non-hit,NaN,ENST00000358273.9,P21359,NM_001042492.3,Glu445Lys,E445K,3.0,2.0,1.0,0.0,0.057,0.343,0.9605,0.096584,0.6491,-0.044299,0.999163,0.812706,-5.505,5.781303,0.562291,6.17,6.17,0.983668,0.65488,0.789613,0.815019,0.489632,-0.3391,0.999537,1.04,-2.67,0.0,0.643356,656.0,0.898995,0.518561,1.0,9.533,26.4,NaN,NaN,NaN,19.0,-48.0,-3.0,24.0,0.0,0.0,0.0,0.0,1.0,0.249,NaN,NaN,9479.0,7.886848,E,445.0,K,-0.011413,89.07
53011,GTGTTTCACCAAACATATTT,CBE,NF1,HT29,PIC,-0.296869,non-hit,EG,ENST00000358273.9,P21359,NM_001042492.3,Glu445Lys,E445K,3.0,2.0,1.0,0.0,0.057,0.343,0.9605,0.096584,0.6491,-0.044299,0.999163,0.812706,-5.505,5.781303,0.562291,6.17,6.17,0.983668,0.65488,0.789613,0.815019,0.489632,-0.3391,0.999537,1.04,-2.67,0.0,0.643356,656.0,0.898995,0.518561,1.0,9.533,26.4,NaN,NaN,NaN,19.0,-48.0,-3.0,24.0,0.0,0.0,0.0,0.0,1.0,0.249,NaN,NaN,9479.0,7.886848,E,445.0,K,-0.011413,89.07

In [79]:
len(duplicates_fragments)

474

In [80]:
234/len(annotated_foldx_control_df) * 100

0.1585806355423932

In [81]:
duplicates_fragments['aa_change'].nunique()

32

In [82]:
duplicates_fragments['Hit_class'].value_counts()

Hit_class
non-hit    474
Name: count, dtype: int64

In [83]:
duplicates_fragments['Guide'].nunique()

39

In [84]:
#drop duplicates including first occurrence
annotated_foldx_control_df = annotated_foldx_control_df.drop_duplicates(
    subset=["Guide", "Editor", "Cell_Line", "Drug", "uniprot_accession", "uniprot_position", "wild_type", "mutated_type", "zscore"], keep=False
)

In [85]:
len(annotated_foldx_control_df)

147085

In [86]:
len(annotated_control_df)-len(annotated_foldx_control_df)

234

In [ ]:
annotated_foldx_control_df.to_csv("data/9_ProtVar/zscores-unambiguous-VEPannotated-processed-gene-expression-foldx-only_dataset-control.csv", index=False)

#### Missing data in FoldX ddG

In [99]:
#Check missing entries in foldX ddG
missing_foldx_ddg = annotated_foldx_control_df[annotated_foldx_control_df['foldx_ddg'].isnull()]
missing_foldx_ddg = missing_foldx_ddg[~missing_foldx_ddg['uniprot_accession'].isin(['P01116', 'P29353', 'Q9UGN5'])]

In [110]:
print(f'Missing entries in foldX ddG: {len(missing_foldx_ddg)} ({len(missing_foldx_ddg)/len(annotated_foldx_control_df[~annotated_foldx_control_df['uniprot_accession'].isin(['P01116', 'P29353', 'Q9UGN5'])]) * 100:.2f}%)')
print(f'Missing entries in foldX ddG due to non-coding variants: {len(missing_foldx_ddg[missing_foldx_ddg["Amino Acid Edits"] == "(NC)"])} ({len(missing_foldx_ddg[missing_foldx_ddg["Amino Acid Edits"] == "(NC)"])/len(missing_foldx_ddg) * 100:.3f}% of the missing)')
print(f'Missing entries in foldX ddG due to Silent and Nonsense variants: {len(missing_foldx_ddg[missing_foldx_ddg["Mutation_Category_enc"].isin([2.0,4.0])] )} ({len(missing_foldx_ddg[missing_foldx_ddg["Mutation_Category_enc"].isin([2.0,4.0])] )/len(missing_foldx_ddg) * 100:.3f}% of the missing)')
print(f'Missing entries in foldX ddG of Missense variants: {len(missing_foldx_ddg[missing_foldx_ddg["Mutation_Category_enc"]==3.0])} ({len(missing_foldx_ddg[missing_foldx_ddg["Mutation_Category_enc"]==3.0])/len(missing_foldx_ddg) * 100:.3f}% of the missing; {len(missing_foldx_ddg[missing_foldx_ddg["Mutation_Category_enc"]==3.0])/len(annotated_foldx_control_df[~(annotated_foldx_control_df['uniprot_accession'].isin(['P01116', 'P29353', 'Q9UGN5'])) & (annotated_foldx_control_df["Mutation_Category_enc"]==3.0)]) * 100:.3f}% of all Missense variants)')

Missing entries in foldX ddG: 76458 (55.31%)
Missing entries in foldX ddG due to non-coding variants: 10016 (13.100% of the missing)
Missing entries in foldX ddG due to Silent and Nonsense variants: 54604 (71.417% of the missing)
Missing entries in foldX ddG of Missense variants: 11838 (15.483% of the missing; 16.081% of all Missense variants)

In [106]:
missing_foldx_ddg['Mutation_Category_enc'].value_counts()

Mutation_Category_enc
2.0    49168
3.0    11838
4.0     5436
0.0     5247
5.0     2540
6.0     1340
1.0      889
Name: count, dtype: int64

In [108]:
annotated_foldx_control_df[~(annotated_foldx_control_df['uniprot_accession'].isin(['P01116', 'P29353', 'Q9UGN5']))]['Mutation_Category_enc'].value_counts()

Mutation_Category_enc
3.0    73617
2.0    49168
4.0     5436
0.0     5247
5.0     2540
6.0     1340
1.0      889
Name: count, dtype: int64

#### Get ddg for plddt<70 in ProtVar webserver

Filter the dataset for variants with AA change and missing values in ddg

In [111]:
annotated_foldx_missing_ddg = annotated_foldx_control_df[(annotated_foldx_control_df['aa_change']!="(NC)") & (annotated_foldx_control_df['foldx_ddg'].isnull())]

In [112]:
#Exclude proteins P01116, P29353, Q9UGN5 for which we will get foldX data later
annotated_foldx_missing_ddg = annotated_foldx_missing_ddg[~annotated_foldx_missing_ddg['uniprot_accession'].isin(['P01116', 'P29353', 'Q9UGN5'])]

In [113]:
len(annotated_foldx_missing_ddg)

66442

In [118]:
annotated_foldx_missing_ddg.head()

,Guide,Editor,Gene,Cell_Line,Drug,zscore,Hit_class,Source,Target Transcript ID,uniprot_accession,RefSeq match transcript (MANE Select),Amino Acid Edits,aa_change,Mutation_Category_enc,IMPACT_enc,TSL,SIFT_pathogenicity,PolyPhen_pathogenicity,REVEL,ClinPred,EVE_SCORE,AlphaMissense_score,BayesDel_noAF_score,DANN_score,DEOGEN2_score,ESM1b_score,Eigen-PC-phred_coding,Eigen-PC-raw_coding,GERP++_NR,GERP++_RS,LIST-S2_score,MPC_rankscore,MPC_score,MVP_score,MetaRNN_score,MetaSVM_score,MutFormer_score,MutationAssessor_score,PROVEAN_score,PrimateAI_pred_enc,VARITY_R_LOO_score,bStatistic,fathmm-XF_coding_score,gMVP_score,phastCons100way_vertebrate,phyloP100way_vertebrate,CADD_PHRED,MaxEntScan_alt,MaxEntScan_diff,MaxEntScan_ref,SpliceAI_pred_DP_AG,SpliceAI_pred_DP_AL,SpliceAI_pred_DP_DG,SpliceAI_pred_DP_DL,SpliceAI_pred_DS_AG,SpliceAI_pred_DS_AL,SpliceAI_pred_DS_DG,SpliceAI_pred_DS_DL,BLOSUM62,LOEUF,mutfunc_exp,ada_score,Gene_expression_expected_counts,Gene_expression_voom,wild_type,uniprot_position,mutated_type,foldx_ddg,plddt
0,AAAAAACATCGTAGTAGCAG,CBE,RICTOR,A375,PIC,0.274277,non-hit,NaN,ENST00000357387.8,Q6R327,NM_152756.5,His1109Tyr,H1109Y,3.0,2.0,1.0,1.0,0.0,0.214,0.46304,NaN,0.0685,-0.402171,0.970933,0.045001,-4.388,5.314964,0.516773,5.75,5.75,0.917608,0.44121,0.44506,0.09349,0.1791,-1.0259,0.000785,0.345,-0.22,1.0,0.094767,226.0,0.800526,NaN,1.0,5.938,20.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.305,NaN,NaN,2813.00,5.531900,H,1109.0,Y,NaN,NaN
3,AAAAAACTGTTTGGGACCTC,CBE,EGFR,A375,PIC,-0.801011,non-hit,NaN,ENST00000275493.7,P00533,NM_005228.5,Leu480Leu,L480L,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.051,NaN,NaN,NaN,21.0,-44.0,-45.0,45.0,0.0,0.0,0.0,0.0,NaN,0.475,-0.01879,NaN,891.97,3.875409,L,480.0,L,NaN,NaN
5,AAAAAATCCTGTCACTTGTG,CBE,PIK3CB,A375,PIC,-0.375589,non-hit,NaN,ENST00000674063.1,P42338,NM_006219.3,Ile160Ile,I160I,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.319,NaN,NaN,3356.00,5.786491,I,160.0,I,NaN,NaN
6,AAAAACAAAACGATTTCCTC,CBE,RICTOR,A375,PIC,0.558912,non-hit,NaN,ENST00000357387.8,Q6R327,NM_152756.5,Asn763Asn,N763N,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.305,NaN,NaN,2813.00,5.531900,N,763.0,N,NaN,NaN
7,AAAAACAAAATTGTGAGTAT,CBE,RAF1,A375,PIC,0.014766,non-hit,NaN,ENST00000251849.9,P04049,NM_002880.4,Asn328Asn,N328N,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.541,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.351,NaN,NaN,7651.70,6.975408,N,328.0,N,NaN,NaN

In [ ]:
annotated_foldx_control_df[(annotated_foldx_control_df['Mutation_Category_enc']==2.0) & ~(annotated_foldx_control_df['foldx_ddg'].isnull())].head()

In [115]:
#Filter for missense mutations only
annotated_foldx_missing_ddg_missense = annotated_foldx_missing_ddg[annotated_foldx_missing_ddg['Mutation_Category_enc']==3.0]

In [119]:
annotated_foldx_missing_ddg_missense.head()

,Guide,Editor,Gene,Cell_Line,Drug,zscore,Hit_class,Source,Target Transcript ID,uniprot_accession,RefSeq match transcript (MANE Select),Amino Acid Edits,aa_change,Mutation_Category_enc,IMPACT_enc,TSL,SIFT_pathogenicity,PolyPhen_pathogenicity,REVEL,ClinPred,EVE_SCORE,AlphaMissense_score,BayesDel_noAF_score,DANN_score,DEOGEN2_score,ESM1b_score,Eigen-PC-phred_coding,Eigen-PC-raw_coding,GERP++_NR,GERP++_RS,LIST-S2_score,MPC_rankscore,MPC_score,MVP_score,MetaRNN_score,MetaSVM_score,MutFormer_score,MutationAssessor_score,PROVEAN_score,PrimateAI_pred_enc,VARITY_R_LOO_score,bStatistic,fathmm-XF_coding_score,gMVP_score,phastCons100way_vertebrate,phyloP100way_vertebrate,CADD_PHRED,MaxEntScan_alt,MaxEntScan_diff,MaxEntScan_ref,SpliceAI_pred_DP_AG,SpliceAI_pred_DP_AL,SpliceAI_pred_DP_DG,SpliceAI_pred_DP_DL,SpliceAI_pred_DS_AG,SpliceAI_pred_DS_AL,SpliceAI_pred_DS_DG,SpliceAI_pred_DS_DL,BLOSUM62,LOEUF,mutfunc_exp,ada_score,Gene_expression_expected_counts,Gene_expression_voom,wild_type,uniprot_position,mutated_type,foldx_ddg,plddt,protvar_input
0,AAAAAACATCGTAGTAGCAG,CBE,RICTOR,A375,PIC,0.274277,non-hit,NaN,ENST00000357387.8,Q6R327,NM_152756.5,His1109Tyr,H1109Y,3.0,2.0,1.0,1.00,0.000,0.214,0.463040,NaN,0.0685,-0.402171,0.970933,0.045001,-4.388,5.314964,0.516773,5.75,5.75,0.917608,0.44121,0.445060,0.093490,0.179100,-1.0259,0.000785,0.345,-0.22,1.0,0.094767,226.0,0.800526,NaN,1.0,5.938,20.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.305,NaN,NaN,2813.0,5.531900,H,1109.0,Y,NaN,NaN,Q6R327 H1109Y
27,AAAAATTCATTCCCTTTCTT,CBE,RICTOR,A375,PIC,0.278889,non-hit,NaN,ENST00000357387.8,Q6R327,NM_152756.5,Ser1084Leu,S1084L,3.0,2.0,1.0,0.00,0.015,0.079,NaN,NaN,0.0772,-0.439000,0.995179,0.071884,-4.127,4.003639,0.347163,5.86,5.86,0.949755,0.37823,0.365045,0.082315,0.108146,-1.0368,0.000550,0.000,-1.89,1.0,0.176085,226.0,0.781873,NaN,1.0,7.280,24.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.0,0.305,NaN,NaN,2813.0,5.531900,S,1084.0,L,NaN,NaN,Q6R327 S1084L
31,AAAACAGAATCATCTCCTGA,CBE,FGFR2,A375,PIC,0.226299,non-hit,NaN,ENST00000358487.10,P21802,NM_000141.5,Val797Ile,V797I,3.0,2.0,1.0,0.00,0.802,0.462,0.992943,0.344692,0.1596,-0.057121,0.998675,0.387678,-9.170,14.486490,0.916744,6.04,6.04,0.934007,0.24798,NaN,0.708370,0.409144,0.5275,0.878436,2.525,-0.63,1.0,0.100700,576.0,0.920146,NaN,1.0,7.867,26.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.185,NaN,NaN,45.0,-0.418456,V,797.0,I,NaN,NaN,P21802 V797I
35,AAAACATAGAGTTCTCCATC,CBE,GAB1,A375,PIC,-0.153032,non-hit,NaN,ENST00000262994.9,Q13480,NM_002039.4,Val286Ile,V286I,3.0,2.0,1.0,0.02,0.005,0.078,0.385430,0.258856,0.0721,-0.388044,0.989555,0.434646,-4.014,2.948381,0.149878,5.80,4.95,0.823718,0.34641,NaN,0.404520,0.168871,-1.0447,0.001867,2.175,-0.53,1.0,0.052804,902.0,0.713530,NaN,1.0,5.314,20.7,NaN,NaN,NaN,2.0,-39.0,41.0,46.0,0.0,0.0,0.0,0.0,3.0,0.470,NaN,NaN,436.0,2.843587,V,286.0,I,NaN,NaN,Q13480 V286I
36,AAAACATGAATGACTGTGTC,CBE,FGFR2,A375,PIC,-0.239779,non-hit,NaN,ENST00000358487.10,P21802,NM_000141.5,Thr821Ile,T821I,3.0,2.0,1.0,0.00,0.909,0.498,0.859950,NaN,0.4352,0.054047,0.998812,0.740500,-3.814,11.267440,0.835754,5.91,5.91,0.895810,0.27021,NaN,0.599038,0.365145,0.3923,0.909801,1.995,-2.65,1.0,0.354806,576.0,0.929820,NaN,1.0,7.266,24.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.185,NaN,NaN,45.0,-0.418456,T,821.0,I,NaN,NaN,P21802 T821I

In [120]:
len(annotated_foldx_missing_ddg_missense)

11838

In [117]:
#Create a new columns with the ProtVar input format 'uniprot_accession' + ' ' + 'aa_change'
annotated_foldx_missing_ddg_missense=annotated_foldx_missing_ddg_missense.copy()
annotated_foldx_missing_ddg_missense['protvar_input'] = annotated_foldx_missing_ddg_missense['uniprot_accession'] + ' ' + annotated_foldx_missing_ddg_missense['aa_change']

In [121]:
#Check if there are Nan values in 'protvar_input'
annotated_foldx_missing_ddg_missense['protvar_input'].isnull().sum()

np.int64(0)

In [123]:
#Create a text file with unique protvar_input values
with open('data/9_ProtVar/ProtVar_input_missing_foldx_ddg_missense.txt', 'w') as f:
    for item in annotated_foldx_missing_ddg_missense['protvar_input'].unique():
        f.write(f"{item}\n")

In [124]:
#Check the len of inputs in the text file
with open('data/9_ProtVar/ProtVar_input_missing_foldx_ddg_missense.txt', 'r') as f:
    lines = f.readlines()
    print(f"Number of lines in the ProtVar input file: {len(lines)}")

Number of lines in the ProtVar input file: 1124

In [125]:
len(annotated_foldx_control_df)

147085

In [ ]:
annotated_foldx_control_df.to_csv("/data/9_ProtVar/zscores-unambiguous-VEPannotated-processed-gene-expression-foldx-control")

Load ProtVar webserver prediction for the missensse variants with missing ddg in the table

In [127]:
missing_ddg_missense_protvar_output = pd.read_csv('data/9_ProtVar/missing_ddg_missense_variants_protvar_output.csv')

In [131]:
len(missing_ddg_missense_protvar_output)

1655

In [137]:
duplicates_input = missing_ddg_missense_protvar_output[missing_ddg_missense_protvar_output['User_input'].duplicated(keep=False)].sort_values('User_input')

In [138]:
len(duplicates_input)

0

In [139]:
duplicates_input.head()

Empty DataFrame
Columns: [User_input, Chromosome, Coordinate, ID, Reference_allele, Alternative_allele, Notes, Gene, Codon_change, Strand, CADD_phred_like_score, Canonical_isoform_transcripts, MANE_transcript, Uniprot_canonical_isoform_(non_canonical), Alternative_isoform_mappings, Protein_name, Amino_acid_position, Amino_acid_change, Consequences, Residue_function_(evidence), Region_function_(evidence), Protein_existence_evidence, Protein_length, Entry_last_updated, Sequence_last_updated, Protein_catalytic_activity, Protein_complex, Protein_sub_cellular_location, Protein_family, Protein_interactions_PROTEIN(gene), Predicted_pockets(energy;per_vol;score;resids), Predicted_interactions(chainA-chainB;a_resids;b_resids;pDockQ), Foldx_prediction(foldxDdg;plddt), Conservation_score, AlphaMissense_pathogenicity(class), EVE_score(class), ESM1b_score, Genomic_location, Cytogenetic_band, Other_identifiers_for_the_variant, Diseases_associated_with_variant, Variants_colocated_at_residue_position, Position_in_structures]
Index: []

In [136]:
#Drop the duplicates (due to codon redudancy) in User_input, keeping the first occurrence
missing_ddg_missense_protvar_output = missing_ddg_missense_protvar_output.drop_duplicates(subset=['User_input'], keep='first')

In [ ]:
missing_ddg_missense_protvar_output.head()

In [140]:
# Extract foldxDdg and plddt values into new columns
missing_ddg_missense_protvar_output[['FoldX_ddg', 'plddt']] = missing_ddg_missense_protvar_output[
    'Foldx_prediction(foldxDdg;plddt)'
].str.extract(r'foldxDdg:([-\d.]+);plddt:([-\d.]+)') # the groups to extract are inside parentheses

# Convert to float
missing_ddg_missense_protvar_output['FoldX_ddg'] = missing_ddg_missense_protvar_output['FoldX_ddg'].astype(float)
missing_ddg_missense_protvar_output['plddt'] = missing_ddg_missense_protvar_output['plddt'].astype(float)

In [141]:
missing_ddg_missense_protvar_output.head()

,User_input,Chromosome,Coordinate,ID,Reference_allele,Alternative_allele,Notes,Gene,Codon_change,Strand,CADD_phred_like_score,Canonical_isoform_transcripts,MANE_transcript,Uniprot_canonical_isoform_(non_canonical),Alternative_isoform_mappings,Protein_name,Amino_acid_position,Amino_acid_change,Consequences,Residue_function_(evidence),Region_function_(evidence),Protein_existence_evidence,Protein_length,Entry_last_updated,Sequence_last_updated,Protein_catalytic_activity,Protein_complex,Protein_sub_cellular_location,Protein_family,Protein_interactions_PROTEIN(gene),Predicted_pockets(energy;per_vol;score;resids),Predicted_interactions(chainA-chainB;a_resids;b_resids;pDockQ),Foldx_prediction(foldxDdg;plddt),Conservation_score,AlphaMissense_pathogenicity(class),EVE_score(class),ESM1b_score,Genomic_location,Cytogenetic_band,Other_identifiers_for_the_variant,Diseases_associated_with_variant,Variants_colocated_at_residue_position,Position_in_structures,FoldX_ddg,plddt
0,Q6R327 H1109Y,5.0,38950523.0,NaN,G,A,NaN,RICTOR,Cau/Uau,-,20.4,[ENSP00000349959.3(ENST00000357387.8)],NaN,Q6R327,Q6R327-3;1109;His/Tyr;missense;[ENSP0000029678...,Rapamycin-insensitive companion of mTOR,1109.0,His/Tyr,missense,NaN,CHAIN-Rapamycin-insensitive companion of mTOR;...,Evidence at protein level,1708.0,2025-02-05,2004-07-05,NaN,Component of the mechanistic target of rapamyc...,Cell membrane;Endoplasmic reticulum membrane;L...,Belongs to the RICTOR family,Q13418(ILK);P42345(MTOR);Q8TCU6(PREX1);P31947(...,NaN,NaN,NaN,0.410,0.0685(BENIGN),NaN,-4.388,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P01106 D2N,8.0,127736597.0,NaN,G,A,NaN,MYC,Gau/Aau,+,22.1,[ENSP00000478887.2(ENST00000621592.8)],NaN,P01106,P01106-3;2;Asp/Asn;missense;[ENSP00000430235.2...,Myc proto-oncogene protein,2.0,Asp/Asn,missense,CONFLICT-in Ref. 9; BAA01374(),CHAIN-Myc proto-oncogene protein;Range:1-454,Evidence at protein level,454.0,2025-02-05,2023-02-22,NaN,Efficient DNA binding requires dimerization wi...,"Nucleus, nucleoplasm;Nucleus, nucleolus;Nucleu...",NaN,Q9UBB4(ATXN10);O15169(AXIN1);O00499-10(BIN1);O...,NaN,NaN,foldxDdg:-0.23776;plddt:55.7,0.938,0.4683(AMBIGUOUS),NaN,-3.721,NaN,NaN,NaN,NaN,NaN,NaN,-0.237760,55.70
2,P21359 V1665I,17.0,31325977.0,NaN,G,A,NaN,NF1,Guu/Auu,+,24.8,[ENSP00000351015.4(ENST00000358273.9)],NaN,P21359,A0A8I5KWR6;1675;Val/Ile;missense;[ENSP00000510...,Neurofibromin,1665.0,Val/Ile,missense,NaN,CHAIN-Neurofibromin;Range:2-2839|DOMAIN-CRAL-T...,Evidence at protein level,2839.0,2025-02-05,1994-06-01,NaN,Interacts with HTR6 (PubMed:23027611),"Nucleus;Nucleus, nucleolus;Cell membrane",NaN,P05067(APP);P01112(HRAS);P34741(SDC2);Q7Z699(S...,NaN,NaN,foldxDdg:0.994221;plddt:87.55,0.910,0.2928(BENIGN),0.118(BENIGN),-7.678,NaN,NaN,NaN,NaN,NaN,NaN,0.994221,87.55
3,P21359 R1958H,17.0,31334898.0,NaN,G,A,NaN,NF1,cGu/cAu,+,33.0,[ENSP00000351015.4(ENST00000358273.9)],NaN,P21359,A0A8I5KWR6;1968;Arg/His;missense;[ENSP00000510...,Neurofibromin,1958.0,Arg/His,missense,NaN,CHAIN-Neurofibromin;Range:2-2839|HELIX;Range:1...,Evidence at protein level,2839.0,2025-02-05,1994-06-01,NaN,Interacts with HTR6 (PubMed:23027611),"Nucleus;Nucleus, nucleolus;Cell membrane",NaN,P05067(APP);P01112(HRAS);P34741(SDC2);Q7Z699(S...,NaN,NaN,foldxDdg:7.7038;plddt:82.33,0.859,0.2687(BENIGN),0.476(UNCERTAIN),-7.027,NaN,NaN,NaN,NaN,NaN,NaN,7.703800,82.33
4,Q6R327 S1084L,5.0,38950597.0,NaN,G,A,NaN,RICTOR,uCa/uUa,-,24.8,[ENSP00000349959.3(ENST00000357387.8)],NaN,Q6R327,Q6R327-3;1084;Ser/Leu;missense;[ENSP0000029678...,Rapamycin-insensitive companion of mTOR,1084.0,Ser/Leu,missense,NaN,CHAIN-Rapamycin-insensitive companion of mTOR;...,Evidence at protein level,1708.0,2025-02-05,2004-07-05,NaN,Component of the mechanistic target of rapamyc...,Cell membrane;Endoplasmic reticulum membrane;L...,Belongs to the RICTOR family,Q13418(ILK);P42345(MTOR);Q8TCU6(PREX1);P31947(...,NaN,NaN,NaN,0.562,0.0772(BENIGN),NaN,-4.127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
annotated_foldx_control_df

Merge the foldx_ddg and plddt scores into the final annotated dataset

In [173]:
# Add the ProtVar input in the annotated dataframe to serve as a key for merging
annotated_foldx_control_df = annotated_foldx_control_df.copy()
annotated_foldx_control_df['protvar_input'] = np.where(
    annotated_foldx_control_df['aa_change'].str.contains(r'\(NC\)', na=False),
    np.nan,
    annotated_foldx_control_df['uniprot_accession'] + ' ' + annotated_foldx_control_df['aa_change']
)

In [151]:
annotated_foldx_control_df.head()

,Guide,Editor,Gene,Cell_Line,Drug,zscore,Hit_class,Source,Target Transcript ID,uniprot_accession,RefSeq match transcript (MANE Select),Amino Acid Edits,aa_change,Mutation_Category_enc,IMPACT_enc,TSL,SIFT_pathogenicity,PolyPhen_pathogenicity,REVEL,ClinPred,EVE_SCORE,AlphaMissense_score,BayesDel_noAF_score,DANN_score,DEOGEN2_score,ESM1b_score,Eigen-PC-phred_coding,Eigen-PC-raw_coding,GERP++_NR,GERP++_RS,LIST-S2_score,MPC_rankscore,MPC_score,MVP_score,MetaRNN_score,MetaSVM_score,MutFormer_score,MutationAssessor_score,PROVEAN_score,PrimateAI_pred_enc,VARITY_R_LOO_score,bStatistic,fathmm-XF_coding_score,gMVP_score,phastCons100way_vertebrate,phyloP100way_vertebrate,CADD_PHRED,MaxEntScan_alt,MaxEntScan_diff,MaxEntScan_ref,SpliceAI_pred_DP_AG,SpliceAI_pred_DP_AL,SpliceAI_pred_DP_DG,SpliceAI_pred_DP_DL,SpliceAI_pred_DS_AG,SpliceAI_pred_DS_AL,SpliceAI_pred_DS_DG,SpliceAI_pred_DS_DL,BLOSUM62,LOEUF,mutfunc_exp,ada_score,Gene_expression_expected_counts,Gene_expression_voom,wild_type,uniprot_position,mutated_type,foldx_ddg,plddt,protvar_input
0,AAAAAACATCGTAGTAGCAG,CBE,RICTOR,A375,PIC,0.274277,non-hit,NaN,ENST00000357387.8,Q6R327,NM_152756.5,His1109Tyr,H1109Y,3.0,2.0,1.0,1.0,0.000,0.214,0.463040,NaN,0.0685,-0.402171,0.970933,0.045001,-4.388,5.314964,0.516773,5.75,5.75,0.917608,0.44121,0.445060,0.093490,0.179100,-1.0259,0.000785,0.345,-0.22,1.0,0.094767,226.0,0.800526,NaN,1.000,5.938,20.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.305,NaN,NaN,2813.00,5.531900,H,1109.0,Y,NaN,NaN,Q6R327 H1109Y
1,AAAAAACTCAACAGCAGTGA,CBE,NRAS,A375,PIC,0.399691,non-hit,NaN,ENST00000369535.5,P01111,NM_002524.5,Leu171Phe,L171F,3.0,2.0,1.0,0.1,NaN,0.141,0.413488,NaN,0.1149,-0.222424,0.993713,0.120039,-5.943,3.683551,0.294249,5.86,5.86,0.865513,0.74516,1.008632,0.619943,0.190982,-0.9613,0.907693,1.385,-1.28,1.0,0.072730,819.0,0.580949,0.628916,1.000,4.055,23.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.550,NaN,NaN,6331.00,6.702081,L,171.0,F,-0.239753,88.23,P01111 L171F
2,AAAAAACTGGCCAGGTGAGC,CBE,PIK3CB,A375,PIC,0.399178,non-hit,NaN,ENST00000674063.1,P42338,NM_006219.3,Thr930Ile,T930I,3.0,2.0,NaN,0.0,0.862,NaN,0.373381,NaN,NaN,-0.058094,0.998396,0.879846,-10.191,4.891242,0.469329,5.63,3.78,NaN,0.73854,NaN,NaN,NaN,0.6434,0.529280,3.705,NaN,0.0,0.365695,856.0,0.310513,NaN,0.998,2.094,25.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.319,NaN,NaN,3356.00,5.786491,T,930.0,I,-0.070749,91.70,P42338 T930I
3,AAAAAACTGTTTGGGACCTC,CBE,EGFR,A375,PIC,-0.801011,non-hit,NaN,ENST00000275493.7,P00533,NM_005228.5,Leu480Leu,L480L,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.051,NaN,NaN,NaN,21.0,-44.0,-45.0,45.0,0.0,0.0,0.0,0.0,NaN,0.475,-0.01879,NaN,891.97,3.875409,L,480.0,L,NaN,NaN,P00533 L480L
4,AAAAAATCCAGCGTCTAAGC,CBE,MYC,A375,PIC,-0.379377,non-hit,NaN,ENST00000621592.8,P01106,NM_002467.6,Asp2Asn,D2N,3.0,2.0,1.0,0.0,0.199,NaN,0.453567,NaN,0.1399,-0.438067,0.984375,NaN,NaN,1.792897,-0.197017,4.31,2.43,0.397160,NaN,NaN,0.733174,0.215208,-0.7405,0.036037,NaN,NaN,1.0,NaN,951.0,0.226082,0.128201,1.000,1.507,22.100,NaN,NaN,NaN,16.0,-14.0,10.0,26.0,0.0,0.0,0.0,0.0,1.0,0.128,NaN,NaN,783.00,3.687539,D,2.0,N,-0.237760,55.70,P01106 D2N

In [174]:
len(annotated_foldx_control_df)

147085

In [167]:
#Merge the predictions 'Foldx_ddg' and 'plddt' into the annotated_foldx_missing_ddg_missense 

merge_predictions_df = annotated_foldx_control_df.merge(
    missing_ddg_missense_protvar_output[['User_input', 'FoldX_ddg', 'plddt']],
    how='left',
    left_on = ['protvar_input'],
    right_on = ['User_input'],
    suffixes=('', '_new')
)

In [160]:
#Fill the NaN values in the original 'foldx_ddg' and 'plddt' columns with the new predictions from the ProtVar server
merge_predictions_df['foldx_ddg'] = merge_predictions_df['foldx_ddg'].combine_first(merge_predictions_df['FoldX_ddg'])
merge_predictions_df['plddt'] = merge_predictions_df['plddt'].combine_first(merge_predictions_df['plddt_new'])

In [169]:
#Drop the auxiliary columns
merge_predictions_df = merge_predictions_df.drop(columns=['protvar_input', 'User_input', 'FoldX_ddg', 'plddt_new'])

In [175]:
merge_predictions_df.head()

,Guide,Editor,Gene,Cell_Line,Drug,zscore,Hit_class,Source,Target Transcript ID,uniprot_accession,RefSeq match transcript (MANE Select),Amino Acid Edits,aa_change,Mutation_Category_enc,IMPACT_enc,TSL,SIFT_pathogenicity,PolyPhen_pathogenicity,REVEL,ClinPred,EVE_SCORE,AlphaMissense_score,BayesDel_noAF_score,DANN_score,DEOGEN2_score,ESM1b_score,Eigen-PC-phred_coding,Eigen-PC-raw_coding,GERP++_NR,GERP++_RS,LIST-S2_score,MPC_rankscore,MPC_score,MVP_score,MetaRNN_score,MetaSVM_score,MutFormer_score,MutationAssessor_score,PROVEAN_score,PrimateAI_pred_enc,VARITY_R_LOO_score,bStatistic,fathmm-XF_coding_score,gMVP_score,phastCons100way_vertebrate,phyloP100way_vertebrate,CADD_PHRED,MaxEntScan_alt,MaxEntScan_diff,MaxEntScan_ref,SpliceAI_pred_DP_AG,SpliceAI_pred_DP_AL,SpliceAI_pred_DP_DG,SpliceAI_pred_DP_DL,SpliceAI_pred_DS_AG,SpliceAI_pred_DS_AL,SpliceAI_pred_DS_DG,SpliceAI_pred_DS_DL,BLOSUM62,LOEUF,mutfunc_exp,ada_score,Gene_expression_expected_counts,Gene_expression_voom,wild_type,uniprot_position,mutated_type,foldx_ddg,plddt
0,AAAAAACATCGTAGTAGCAG,CBE,RICTOR,A375,PIC,0.274277,non-hit,NaN,ENST00000357387.8,Q6R327,NM_152756.5,His1109Tyr,H1109Y,3.0,2.0,1.0,1.0,0.000,0.214,0.463040,NaN,0.0685,-0.402171,0.970933,0.045001,-4.388,5.314964,0.516773,5.75,5.75,0.917608,0.44121,0.445060,0.093490,0.179100,-1.0259,0.000785,0.345,-0.22,1.0,0.094767,226.0,0.800526,NaN,1.000,5.938,20.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.305,NaN,NaN,2813.00,5.531900,H,1109.0,Y,NaN,NaN
1,AAAAAACTCAACAGCAGTGA,CBE,NRAS,A375,PIC,0.399691,non-hit,NaN,ENST00000369535.5,P01111,NM_002524.5,Leu171Phe,L171F,3.0,2.0,1.0,0.1,NaN,0.141,0.413488,NaN,0.1149,-0.222424,0.993713,0.120039,-5.943,3.683551,0.294249,5.86,5.86,0.865513,0.74516,1.008632,0.619943,0.190982,-0.9613,0.907693,1.385,-1.28,1.0,0.072730,819.0,0.580949,0.628916,1.000,4.055,23.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.550,NaN,NaN,6331.00,6.702081,L,171.0,F,-0.239753,88.23
2,AAAAAACTGGCCAGGTGAGC,CBE,PIK3CB,A375,PIC,0.399178,non-hit,NaN,ENST00000674063.1,P42338,NM_006219.3,Thr930Ile,T930I,3.0,2.0,NaN,0.0,0.862,NaN,0.373381,NaN,NaN,-0.058094,0.998396,0.879846,-10.191,4.891242,0.469329,5.63,3.78,NaN,0.73854,NaN,NaN,NaN,0.6434,0.529280,3.705,NaN,0.0,0.365695,856.0,0.310513,NaN,0.998,2.094,25.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.319,NaN,NaN,3356.00,5.786491,T,930.0,I,-0.070749,91.70
3,AAAAAACTGTTTGGGACCTC,CBE,EGFR,A375,PIC,-0.801011,non-hit,NaN,ENST00000275493.7,P00533,NM_005228.5,Leu480Leu,L480L,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.051,NaN,NaN,NaN,21.0,-44.0,-45.0,45.0,0.0,0.0,0.0,0.0,NaN,0.475,-0.01879,NaN,891.97,3.875409,L,480.0,L,NaN,NaN
4,AAAAAATCCAGCGTCTAAGC,CBE,MYC,A375,PIC,-0.379377,non-hit,NaN,ENST00000621592.8,P01106,NM_002467.6,Asp2Asn,D2N,3.0,2.0,1.0,0.0,0.199,NaN,0.453567,NaN,0.1399,-0.438067,0.984375,NaN,NaN,1.792897,-0.197017,4.31,2.43,0.397160,NaN,NaN,0.733174,0.215208,-0.7405,0.036037,NaN,NaN,1.0,NaN,951.0,0.226082,0.128201,1.000,1.507,22.100,NaN,NaN,NaN,16.0,-14.0,10.0,26.0,0.0,0.0,0.0,0.0,1.0,0.128,NaN,NaN,783.00,3.687539,D,2.0,N,-0.237760,55.70

In [172]:
# Save the final FoldX annotated dataset
merge_predictions_df.to_csv("data/9_ProtVar/zscores-unambiguous-VEPannotated-processed-gene-expression-foldx-control.csv", index=False)

# Protein Pockets Predictions

In [4]:
#Load ProtVar protein pockets dataset
pockets_protvar=pd.read_csv("/data/benchmarks/genomic_annot/2024.05.28_pockets.tsv", sep="\t")

In [5]:
pockets_protvar.shape

(547401, 8)

In [6]:
pockets_protvar.head()

,struct_id,pocket_id,pocket_rad_gyration,pocket_energy_per_vol,pocket_buriedness,pocket_resid,pocket_plddt_mean,pocket_score_combined_scaled
0,A0A024R1R8-F1,1,4.042788,0.316535,0.772959,"{21,22,23,24,25,26,28,29,32}",83.937778,283.034096
1,A0A024R1R8-F1,2,3.175737,0.347111,0.808219,"{12,13,14,15,16,17}",61.206667,102.718057
2,A0A024RBG1-F1,1,7.310256,0.435597,0.856184,"{2,3,4,5,6,7,8,9,10,18,20,21,22,39,40,41,42,47...",89.456190,979.457587
3,A0A024RBG1-F1,2,6.350910,0.389675,0.814896,"{54,57,58,60,61,62,64,65,67,68,69,73,74,75,76,...",83.186923,938.222063
4,A0A024RBG1-F1,3,3.827945,0.378204,0.806045,"{1,2,3,4,5,6,109,110,112,113,114}",77.053636,422.703190

In [7]:
# Separate 'struct_id' into 'uniprot_accession' and 'alphafold_fragment_id'
pockets_protvar[['uniprot_accession', 'alphafold_fragment_id']] = pockets_protvar['struct_id'].str.split('-', expand=True)

In [8]:
# Reorder columns
cols = pockets_protvar.columns.tolist()
idx = cols.index('struct_id')
cols.remove('uniprot_accession')
cols.remove('alphafold_fragment_id')
cols[idx+1:idx+1] = ['uniprot_accession', 'alphafold_fragment_id']
pockets_protvar = pockets_protvar[cols]

In [9]:
pockets_protvar.head()

,struct_id,uniprot_accession,alphafold_fragment_id,pocket_id,pocket_rad_gyration,pocket_energy_per_vol,pocket_buriedness,pocket_resid,pocket_plddt_mean,pocket_score_combined_scaled
0,A0A024R1R8-F1,A0A024R1R8,F1,1,4.042788,0.316535,0.772959,"{21,22,23,24,25,26,28,29,32}",83.937778,283.034096
1,A0A024R1R8-F1,A0A024R1R8,F1,2,3.175737,0.347111,0.808219,"{12,13,14,15,16,17}",61.206667,102.718057
2,A0A024RBG1-F1,A0A024RBG1,F1,1,7.310256,0.435597,0.856184,"{2,3,4,5,6,7,8,9,10,18,20,21,22,39,40,41,42,47...",89.456190,979.457587
3,A0A024RBG1-F1,A0A024RBG1,F1,2,6.350910,0.389675,0.814896,"{54,57,58,60,61,62,64,65,67,68,69,73,74,75,76,...",83.186923,938.222063
4,A0A024RBG1-F1,A0A024RBG1,F1,3,3.827945,0.378204,0.806045,"{1,2,3,4,5,6,109,110,112,113,114}",77.053636,422.703190

### Filter for the proteins of interest
(Proteins used in EG and MC excluding proteins for which the studies use an alternative isoform - 'P01116', 'P29353', 'Q9UGN5')

In [10]:
#Load the transcript mapping ID dataset
transcriptID_mapping = pd.read_csv('/data/benchmarks/genomic_annot/transcriptID_mapping.csv', sep=';')

In [25]:
uniprot_canonical_isoforms = transcriptID_mapping[transcriptID_mapping['is_canonical_in_uniprot']==True]['UniProtID_global']

pockets_proteins_of_interest = pockets_protvar[pockets_protvar['uniprot_accession'].isin(uniprot_canonical_isoforms)]

In [26]:
pockets_proteins_of_interest.head()

,struct_id,uniprot_accession,alphafold_fragment_id,pocket_id,pocket_rad_gyration,pocket_energy_per_vol,pocket_buriedness,pocket_resid,pocket_plddt_mean,pocket_score_combined_scaled
25613,O00329-F1,O00329,F1,1,10.879865,0.433109,0.858808,"{168,169,170,171,172,173,174,175,176,183,246,2...",91.358046,998.316249
25614,O00329-F1,O00329,F1,2,11.488051,0.406961,0.834593,"{9,10,11,12,13,14,15,16,37,38,39,40,41,44,84,8...",88.065143,993.680625
25615,O00329-F1,O00329,F1,3,9.027423,0.374690,0.798281,"{351,352,512,514,515,516,517,518,519,520,521,5...",88.590833,992.419972
25616,O00329-F1,O00329,F1,4,6.871395,0.451481,0.899366,"{107,108,109,110,112,113,114,116,144,147,148,1...",82.355610,990.932366
25617,O00329-F1,O00329,F1,5,8.343294,0.382821,0.772757,"{344,348,350,351,352,353,357,389,393,394,415,4...",89.253393,985.072654

In [27]:
pockets_proteins_of_interest.shape

(1391, 10)

### Explode the amino acid residues columns - 1 residue per row

In [91]:
pockets_proteins_of_interest['pocket_resid'].apply(type).value_counts()

pocket_resid
<class 'str'>    1391
Name: count, dtype: int64

In [92]:
#Convert the strings to a list of int
pockets_proteins_of_interest['pocket_resid'] = pockets_proteins_of_interest['pocket_resid'].apply(
    lambda x: list(map(int, x.strip('{}').split(',')))
)

/tmp/ipykernel_1353803/129696872.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pockets_proteins_of_interest['pocket_resid'] = pockets_proteins_of_interest['pocket_resid'].apply(

In [93]:
#Explode the 'pocket_resid' column
pockets_proteins_of_interest=pockets_proteins_of_interest.explode('pocket_resid').reset_index(drop=True)

In [95]:
pockets_proteins_of_interest.shape

(24892, 10)

In [96]:
pockets_proteins_of_interest.head()

,struct_id,uniprot_accession,alphafold_fragment_id,pocket_id,pocket_rad_gyration,pocket_energy_per_vol,pocket_buriedness,pocket_resid,pocket_plddt_mean,pocket_score_combined_scaled
0,O00329-F1,O00329,F1,1,10.879865,0.433109,0.858808,168,91.358046,998.316249
1,O00329-F1,O00329,F1,1,10.879865,0.433109,0.858808,169,91.358046,998.316249
2,O00329-F1,O00329,F1,1,10.879865,0.433109,0.858808,170,91.358046,998.316249
3,O00329-F1,O00329,F1,1,10.879865,0.433109,0.858808,171,91.358046,998.316249
4,O00329-F1,O00329,F1,1,10.879865,0.433109,0.858808,172,91.358046,998.316249

### Choose the minimum buriedness for the residues that are presente in +1 pocket

In [98]:
duplicates_pockets = pockets_proteins_of_interest[pockets_proteins_of_interest.duplicated(subset=['uniprot_accession', 'pocket_resid'], keep=False)].sort_values(by=['uniprot_accession', 'pocket_resid'])

In [99]:
duplicates_pockets.head()

,struct_id,uniprot_accession,alphafold_fragment_id,pocket_id,pocket_rad_gyration,pocket_energy_per_vol,pocket_buriedness,pocket_resid,pocket_plddt_mean,pocket_score_combined_scaled
472,O00329-F1,O00329,F1,10,5.462578,0.343440,0.779614,6,71.682105,805.812079
1175,O00329-F1,O00329,F1,53,3.109146,0.348189,0.813559,6,68.362500,139.693102
473,O00329-F1,O00329,F1,10,5.462578,0.343440,0.779614,7,71.682105,805.812079
1176,O00329-F1,O00329,F1,53,3.109146,0.348189,0.813559,7,68.362500,139.693102
474,O00329-F1,O00329,F1,10,5.462578,0.343440,0.779614,8,71.682105,805.812079

In [100]:
len(duplicates_pockets)

16829

In [101]:
mask_min_buriedness = pockets_proteins_of_interest['pocket_buriedness'] == pockets_proteins_of_interest.groupby(
    ['uniprot_accession', 'pocket_resid'])['pocket_buriedness'].transform('min')

pockets_min_buriedness =pockets_proteins_of_interest[mask_min_buriedness].copy().reset_index(drop=True)

# Rename the column to be clear about what it represents
pockets_min_buriedness.rename(columns={'pocket_buriedness': 'min_pocket_buriedness'}, inplace=True)

In [102]:
pockets_min_buriedness.head()

,struct_id,uniprot_accession,alphafold_fragment_id,pocket_id,pocket_rad_gyration,pocket_energy_per_vol,min_pocket_buriedness,pocket_resid,pocket_plddt_mean,pocket_score_combined_scaled
0,O00329-F1,O00329,F1,1,10.879865,0.433109,0.858808,172,91.358046,998.316249
1,O00329-F1,O00329,F1,1,10.879865,0.433109,0.858808,173,91.358046,998.316249
2,O00329-F1,O00329,F1,1,10.879865,0.433109,0.858808,248,91.358046,998.316249
3,O00329-F1,O00329,F1,1,10.879865,0.433109,0.858808,258,91.358046,998.316249
4,O00329-F1,O00329,F1,1,10.879865,0.433109,0.858808,260,91.358046,998.316249

In [103]:
len(pockets_min_buriedness)

15239

In [104]:
duplicates_pockets_min_burid = pockets_min_buriedness[pockets_min_buriedness.duplicated(subset=['uniprot_accession', 'pocket_resid'], keep=False)].sort_values(by=['uniprot_accession', 'pocket_resid'])

In [105]:
len(duplicates_pockets_min_burid)

0

In [106]:
pockets_min_buriedness[(pockets_min_buriedness['uniprot_accession']=='O00329') & (pockets_min_buriedness['pocket_resid']==11)]

,struct_id,uniprot_accession,alphafold_fragment_id,pocket_id,pocket_rad_gyration,pocket_energy_per_vol,min_pocket_buriedness,pocket_resid,pocket_plddt_mean,pocket_score_combined_scaled
283,O00329-F1,O00329,F1,10,5.462578,0.34344,0.779614,11,71.682105,805.812079

In [108]:
pockets_proteins_of_interest[(pockets_proteins_of_interest['uniprot_accession']=='O00329') & (pockets_proteins_of_interest['pocket_resid']==11)]

,struct_id,uniprot_accession,alphafold_fragment_id,pocket_id,pocket_rad_gyration,pocket_energy_per_vol,pocket_buriedness,pocket_resid,pocket_plddt_mean,pocket_score_combined_scaled
89,O00329-F1,O00329,F1,2,11.488051,0.406961,0.834593,11,88.065143,993.680625
475,O00329-F1,O00329,F1,10,5.462578,0.343440,0.779614,11,71.682105,805.812079

### Merge into the annotated dataset
the annotated_control_foldx_df

In [121]:
annotated_control_foldx_df.head()

,Guide,Editor,Gene,Cell_Line,Drug,zscore,Hit_class,Source,Target Transcript ID,uniprot_accession,RefSeq match transcript (MANE Select),Amino Acid Edits,aa_change,Mutation_Category_enc,IMPACT_enc,TSL,SIFT_pathogenicity,PolyPhen_pathogenicity,REVEL,ClinPred,EVE_SCORE,AlphaMissense_score,BayesDel_noAF_score,DANN_score,DEOGEN2_score,ESM1b_score,Eigen-PC-phred_coding,Eigen-PC-raw_coding,GERP++_NR,GERP++_RS,LIST-S2_score,MPC_rankscore,MPC_score,MVP_score,MetaRNN_score,MetaSVM_score,MutFormer_score,MutationAssessor_score,PROVEAN_score,PrimateAI_pred_enc,VARITY_R_LOO_score,bStatistic,fathmm-XF_coding_score,gMVP_score,phastCons100way_vertebrate,phyloP100way_vertebrate,CADD_PHRED,MaxEntScan_alt,MaxEntScan_diff,MaxEntScan_ref,SpliceAI_pred_DP_AG,SpliceAI_pred_DP_AL,SpliceAI_pred_DP_DG,SpliceAI_pred_DP_DL,SpliceAI_pred_DS_AG,SpliceAI_pred_DS_AL,SpliceAI_pred_DS_DG,SpliceAI_pred_DS_DL,BLOSUM62,LOEUF,mutfunc_exp,ada_score,Gene_expression_expected_counts,Gene_expression_voom,wild_type,uniprot_position,mutated_type,foldx_ddg,plddt
0,AAAAAACATCGTAGTAGCAG,CBE,RICTOR,A375,PIC,0.274277,non-hit,NaN,ENST00000357387.8,Q6R327,NM_152756.5,His1109Tyr,H1109Y,3.0,2.0,1.0,1.0,0.000,0.214,0.463040,NaN,0.0685,-0.402171,0.970933,0.045001,-4.388,5.314964,0.516773,5.75,5.75,0.917608,0.44121,0.445060,0.093490,0.179100,-1.0259,0.000785,0.345,-0.22,1.0,0.094767,226.0,0.800526,NaN,1.000,5.938,20.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.305,NaN,NaN,2813.00,5.531900,H,1109.0,Y,NaN,NaN
1,AAAAAACTCAACAGCAGTGA,CBE,NRAS,A375,PIC,0.399691,non-hit,NaN,ENST00000369535.5,P01111,NM_002524.5,Leu171Phe,L171F,3.0,2.0,1.0,0.1,NaN,0.141,0.413488,NaN,0.1149,-0.222424,0.993713,0.120039,-5.943,3.683551,0.294249,5.86,5.86,0.865513,0.74516,1.008632,0.619943,0.190982,-0.9613,0.907693,1.385,-1.28,1.0,0.072730,819.0,0.580949,0.628916,1.000,4.055,23.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.550,NaN,NaN,6331.00,6.702081,L,171.0,F,-0.239753,88.23
2,AAAAAACTGGCCAGGTGAGC,CBE,PIK3CB,A375,PIC,0.399178,non-hit,NaN,ENST00000674063.1,P42338,NM_006219.3,Thr930Ile,T930I,3.0,2.0,NaN,0.0,0.862,NaN,0.373381,NaN,NaN,-0.058094,0.998396,0.879846,-10.191,4.891242,0.469329,5.63,3.78,NaN,0.73854,NaN,NaN,NaN,0.6434,0.529280,3.705,NaN,0.0,0.365695,856.0,0.310513,NaN,0.998,2.094,25.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.319,NaN,NaN,3356.00,5.786491,T,930.0,I,-0.070749,91.70
3,AAAAAACTGTTTGGGACCTC,CBE,EGFR,A375,PIC,-0.801011,non-hit,NaN,ENST00000275493.7,P00533,NM_005228.5,Leu480Leu,L480L,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.051,NaN,NaN,NaN,21.0,-44.0,-45.0,45.0,0.0,0.0,0.0,0.0,NaN,0.475,-0.01879,NaN,891.97,3.875409,L,480.0,L,NaN,NaN
4,AAAAAATCCAGCGTCTAAGC,CBE,MYC,A375,PIC,-0.379377,non-hit,NaN,ENST00000621592.8,P01106,NM_002467.6,Asp2Asn,D2N,3.0,2.0,1.0,0.0,0.199,NaN,0.453567,NaN,0.1399,-0.438067,0.984375,NaN,NaN,1.792897,-0.197017,4.31,2.43,0.397160,NaN,NaN,0.733174,0.215208,-0.7405,0.036037,NaN,NaN,1.0,NaN,951.0,0.226082,0.128201,1.000,1.507,22.100,NaN,NaN,NaN,16.0,-14.0,10.0,26.0,0.0,0.0,0.0,0.0,1.0,0.128,NaN,NaN,783.00,3.687539,D,2.0,N,-0.237760,55.70

In [120]:
annotated_control_foldx_df['uniprot_position'] = annotated_control_foldx_df['uniprot_position'].astype('float64')
pockets_min_buriedness['pocket_resid'] = pockets_min_buriedness['pocket_resid'].astype('float64')

In [111]:
11.0 == 11

True

In [122]:
annotated_control_foldx_pocket_df = annotated_control_foldx_df.merge(
    pockets_min_buriedness[['uniprot_accession', 'pocket_resid', 'pocket_id', 'min_pocket_buriedness', 'pocket_plddt_mean', 'pocket_score_combined_scaled']],
    left_on= ['uniprot_accession', 'uniprot_position'],
    right_on= ['uniprot_accession', 'pocket_resid'],
    how= 'left'
)

In [125]:
#Drop and rename columns for clarity
annotated_control_foldx_pocket_df.drop(columns=['pocket_resid'], inplace=True)
annotated_control_foldx_pocket_df.rename(columns={'plddt': 'alphafold_plddt'}, inplace=True)

In [129]:
annotated_control_foldx_pocket_df.head()

,Guide,Editor,Gene,Cell_Line,Drug,zscore,Hit_class,Source,Target Transcript ID,uniprot_accession,RefSeq match transcript (MANE Select),Amino Acid Edits,aa_change,Mutation_Category_enc,IMPACT_enc,TSL,SIFT_pathogenicity,PolyPhen_pathogenicity,REVEL,ClinPred,EVE_SCORE,AlphaMissense_score,BayesDel_noAF_score,DANN_score,DEOGEN2_score,ESM1b_score,Eigen-PC-phred_coding,Eigen-PC-raw_coding,GERP++_NR,GERP++_RS,LIST-S2_score,MPC_rankscore,MPC_score,MVP_score,MetaRNN_score,MetaSVM_score,MutFormer_score,MutationAssessor_score,PROVEAN_score,PrimateAI_pred_enc,VARITY_R_LOO_score,bStatistic,fathmm-XF_coding_score,gMVP_score,phastCons100way_vertebrate,phyloP100way_vertebrate,CADD_PHRED,MaxEntScan_alt,MaxEntScan_diff,MaxEntScan_ref,SpliceAI_pred_DP_AG,SpliceAI_pred_DP_AL,SpliceAI_pred_DP_DG,SpliceAI_pred_DP_DL,SpliceAI_pred_DS_AG,SpliceAI_pred_DS_AL,SpliceAI_pred_DS_DG,SpliceAI_pred_DS_DL,BLOSUM62,LOEUF,mutfunc_exp,ada_score,Gene_expression_expected_counts,Gene_expression_voom,wild_type,uniprot_position,mutated_type,foldx_ddg,alphafold_plddt,pocket_id,min_pocket_buriedness,pocket_plddt_mean,pocket_score_combined_scaled
0,AAAAAACATCGTAGTAGCAG,CBE,RICTOR,A375,PIC,0.274277,non-hit,NaN,ENST00000357387.8,Q6R327,NM_152756.5,His1109Tyr,H1109Y,3.0,2.0,1.0,1.0,0.000,0.214,0.463040,NaN,0.0685,-0.402171,0.970933,0.045001,-4.388,5.314964,0.516773,5.75,5.75,0.917608,0.44121,0.445060,0.093490,0.179100,-1.0259,0.000785,0.345,-0.22,1.0,0.094767,226.0,0.800526,NaN,1.000,5.938,20.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.305,NaN,NaN,2813.00,5.531900,H,1109.0,Y,NaN,NaN,NaN,NaN,NaN,NaN
1,AAAAAACTCAACAGCAGTGA,CBE,NRAS,A375,PIC,0.399691,non-hit,NaN,ENST00000369535.5,P01111,NM_002524.5,Leu171Phe,L171F,3.0,2.0,1.0,0.1,NaN,0.141,0.413488,NaN,0.1149,-0.222424,0.993713,0.120039,-5.943,3.683551,0.294249,5.86,5.86,0.865513,0.74516,1.008632,0.619943,0.190982,-0.9613,0.907693,1.385,-1.28,1.0,0.072730,819.0,0.580949,0.628916,1.000,4.055,23.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.550,NaN,NaN,6331.00,6.702081,L,171.0,F,-0.239753,88.23,NaN,NaN,NaN,NaN
2,AAAAAACTGGCCAGGTGAGC,CBE,PIK3CB,A375,PIC,0.399178,non-hit,NaN,ENST00000674063.1,P42338,NM_006219.3,Thr930Ile,T930I,3.0,2.0,NaN,0.0,0.862,NaN,0.373381,NaN,NaN,-0.058094,0.998396,0.879846,-10.191,4.891242,0.469329,5.63,3.78,NaN,0.73854,NaN,NaN,NaN,0.6434,0.529280,3.705,NaN,0.0,0.365695,856.0,0.310513,NaN,0.998,2.094,25.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.319,NaN,NaN,3356.00,5.786491,T,930.0,I,-0.070749,91.70,10.0,0.848224,90.132188,949.413840
3,AAAAAACTGTTTGGGACCTC,CBE,EGFR,A375,PIC,-0.801011,non-hit,NaN,ENST00000275493.7,P00533,NM_005228.5,Leu480Leu,L480L,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.051,NaN,NaN,NaN,21.0,-44.0,-45.0,45.0,0.0,0.0,0.0,0.0,NaN,0.475,-0.01879,NaN,891.97,3.875409,L,480.0,L,NaN,NaN,6.0,0.808046,94.882812,975.087068
4,AAAAAATCCAGCGTCTAAGC,CBE,MYC,A375,PIC,-0.379377,non-hit,NaN,ENST00000621592.8,P01106,NM_002467.6,Asp2Asn,D2N,3.0,2.0,1.0,0.0,0.199,NaN,0.453567,NaN,0.1399,-0.438067,0.984375,NaN,NaN,1.792897,-0.197017,4.31,2.43,0.397160,NaN,NaN,0.733174,0.215208,-0.7405,0.036037,NaN,NaN,1.0,NaN,951.0,0.226082,0.128201,1.000,1.507,22.100,NaN,NaN,NaN,16.0,-14.0,10.0,26.0,0.0,0.0,0.0,0.0,1.0,0.128,NaN,NaN,783.00,3.687539,D,2.0,N,-0.237760,55.70,NaN,NaN,NaN,NaN

In [130]:
len(annotated_control_foldx_pocket_df)

147085

In [131]:
#Save current annotated df
annotated_control_foldx_pocket_df.to_csv("/data/benchmarks/genomic_annot/zscores-unambiguous-VEPannotated-processed-gene-expression-foldx-pocket-control.csv", index=False)